package ecosystem

const (
	NameGo         = "go"
	NameJavaScript = "javascript"
	NameTypescript = "typescript"
	NameNode       = "node"
	NamePython     = "python"
	NameRust       = "rust"
	NameJava       = "java"
	NameDotnet     = "dotnet"
	NameContainer  = "container"
	NameDocker     = NameContainer // Deprecated: use NameContainer.
	NameTerraform  = "terraform"
	NameRuby       = "ruby"
	NamePHP        = "php"
	NameScala      = "scala"
	NameCpp        = "cpp"
	NameHelm       = "helm"
	NameAnsible    = "ansible"
	NameShell      = "shell"
	NameElixir     = "elixir"
	NameDart       = "dart"
	NameSwift      = "swift"
	NameHaskell    = "haskell"
	NameClojure    = "clojure"
	NameBazel      = "bazel"
	NameNix        = "nix"
	NamePerl       = "perl"
	NameR          = "r"
	NameLua        = "lua"
	NameZig        = "zig"
	NamePowerShell = "powershell"
	NameKotlin     = "kotlin"
	NameAWS        = "aws"
	NameGCP        = "gcp"
	NameAzure      = "azure"
)
