package shellenv

import (
	"strings"
	"testing"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

func TestGenerateStarshipToml(t *testing.T) {
	got, err := GenerateStarshipToml()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if got.Path != ".starship.toml" {
		t.Errorf("Path = %q, want %q", got.Path, ".starship.toml")
	}
	if got.Mode != 0o644 {
		t.Errorf("Mode = %#o, want %#o", got.Mode, 0o644)
	}
	if got.Strategy != types.Overwrite {
		t.Errorf("Strategy = %v, want Overwrite", got.Strategy)
	}

	content := string(got.Content)

	if len(content) == 0 {
		t.Fatal("generated content is empty")
	}

	// Verify custom.qsdev sections are present.
	for _, section := range []string{"[custom.qsdev]", "[custom.qsdev_security]", "[custom.qsdev_tools]"} {
		if !strings.Contains(content, section) {
			t.Errorf("content does not contain section %q", section)
		}
	}

	// Verify references to qsdev environment variables.
	for _, envVar := range []string{"QSDEV_PROJECT_NAME", "QSDEV_SECURITY_PROFILE", "QSDEV_TOOL_COUNT"} {
		if !strings.Contains(content, envVar) {
			t.Errorf("content does not reference %q", envVar)
		}
	}

	// The file replaces the user's own starship config while active; the
	// header must say so and explain how to keep a personal prompt.
	if !strings.HasPrefix(content, "# Generated by qsdev") || !strings.Contains(content, "replaces your personal starship.toml") {
		t.Errorf("content lacks the replacement notice header:\n%s", content)
	}
}

func TestGenerateStarshipToml_ContainsDescriptions(t *testing.T) {
	got, err := GenerateStarshipToml()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(got.Content)

	// Each section should have a description.
	descriptions := []string{
		"Active qsdev project",
		"qsdev security profile",
		"Active tool count",
	}
	for _, desc := range descriptions {
		if !strings.Contains(content, desc) {
			t.Errorf("content does not contain description %q", desc)
		}
	}
}

// TestStarshipNixContent proves STARSHIP_CONFIG is anchored at the devenv root:
// a relative path resolved against the working directory only worked at the
// project root and fell back to the default prompt in every subdirectory.
func TestStarshipNixContent(t *testing.T) {
	got := string(StarshipNixContent())
	want := `  env.STARSHIP_CONFIG = "${config.devenv.root}/.starship.toml";`
	if got != want {
		t.Errorf("StarshipNixContent() = %q, want %q", got, want)
	}
}
