package shellenv

import (
	"fmt"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/branding"
	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// StarshipConfigPath is the project-relative path of the generated starship
// configuration.
const StarshipConfigPath = ".starship.toml"

// StarshipNixContent returns the devenv.nix fragment that points starship at
// the generated configuration. The path is anchored at the devenv root:
// starship resolves a relative STARSHIP_CONFIG against the current directory,
// so a bare ".starship.toml" is found only at the project root and every
// subdirectory silently falls back to the default prompt.
func StarshipNixContent() []byte {
	return []byte(fmt.Sprintf("  env.STARSHIP_CONFIG = \"${config.devenv.root}/%s\";", StarshipConfigPath))
}

// GenerateStarshipToml produces a .starship.toml configuration file with
// custom qsdev prompt segments showing project name, security profile, and
// active tool count.
func GenerateStarshipToml() (*types.GeneratedFile, error) {
	b := branding.Get()
	prefix := b.EnvPrefix
	app := b.AppName
	var s strings.Builder

	// Starship reads exactly one config file and has no include mechanism, so
	// say plainly that this one stands in for the user's own while the devenv
	// shell is active, and how to keep a personal prompt.
	fmt.Fprintf(&s, "# Generated by %s (starship-integration).\n", app)
	s.WriteString("# Inside the devenv shell STARSHIP_CONFIG points at this file, so it\n")
	s.WriteString("# replaces your personal starship.toml for the session. To keep your own\n")
	s.WriteString("# prompt, copy the [custom.*] tables below into ~/.config/starship.toml\n")
	fmt.Fprintf(&s, "# and run `%s disable starship-integration`.\n\n", app)

	fmt.Fprintf(&s, "[custom.%s]\n", app)
	fmt.Fprintf(&s, "command = \"echo $%sPROJECT_NAME\"\n", prefix)
	fmt.Fprintf(&s, "when = 'test -n \"$%sPROJECT_NAME\"'\n", prefix)
	s.WriteString("format = \"[$output]($style) \"\n")
	s.WriteString("style = \"bold cyan\"\n")
	fmt.Fprintf(&s, "description = \"Active %s project\"\n", app)
	s.WriteString("\n")

	fmt.Fprintf(&s, "[custom.%s_security]\n", app)
	s.WriteString("command = '''\n")
	fmt.Fprintf(&s, "  case \"$%sSECURITY_PROFILE\" in\n", prefix)
	s.WriteString("    enhanced) echo \"\xf0\x9f\x94\x92\" ;;\n")
	s.WriteString("    strict)   echo \"\xf0\x9f\x94\x90\" ;;\n")
	s.WriteString("    *)        echo \"\xf0\x9f\x9b\xa1\" ;;\n")
	s.WriteString("  esac\n")
	s.WriteString("'''\n")
	fmt.Fprintf(&s, "when = 'test -n \"$%sSECURITY_PROFILE\"'\n", prefix)
	s.WriteString("format = \"[$output]($style) \"\n")
	s.WriteString("style = \"green\"\n")
	fmt.Fprintf(&s, "description = \"%s security profile\"\n", app)
	s.WriteString("\n")

	fmt.Fprintf(&s, "[custom.%s_tools]\n", app)
	fmt.Fprintf(&s, "command = \"echo ${%sTOOL_COUNT:-0}\"\n", prefix)
	fmt.Fprintf(&s, "when = 'test -n \"$%sPROJECT_NAME\"'\n", prefix)
	s.WriteString("format = \"[$output tools]($style) \"\n")
	s.WriteString("style = \"dimmed white\"\n")
	s.WriteString("description = \"Active tool count\"\n")

	return &types.GeneratedFile{
		Path:     StarshipConfigPath,
		Content:  []byte(s.String()),
		Mode:     fileutil.ModeReadWrite,
		Strategy: types.Overwrite,
	}, nil
}
