package branding

import (
	"sync/atomic"

	gdevinstance "fastcat.org/go/gdev/instance"
)

// GitHubActionsOIDCIssuer is the OIDC token issuer for keyless (Sigstore /
// cosign) signatures produced by GitHub Actions workflows on github.com.
const GitHubActionsOIDCIssuer = "https://token.actions.githubusercontent.com"

// ReleaseWorkflow is the file name of the GitHub Actions workflow that builds,
// signs, and publishes release artifacts (GoReleaser keyless cosign on a tag
// push). It is the workflow whose signing identity release verification pins to.
const ReleaseWorkflow = "release.yml"

type Config struct {
	AppName       string
	ConfigFile    string
	LocalConfig   string
	StateDir      string
	EnvLogVar     string
	EnvLogDirVar  string
	EnvNoUpdate   string
	EnvPrefix     string
	LogFilePrefix string
	TempPrefix    string
	GitHubOwner   string
	GitHubRepo    string
}

func Default() Config {
	return Config{
		AppName:       "qsdev",
		ConfigFile:    ".qsdev.yaml",
		LocalConfig:   ".qsdev.local.yaml",
		StateDir:      ".devinit",
		EnvLogVar:     "QSDEV_LOG",
		EnvLogDirVar:  "QSDEV_LOG_DIR",
		EnvNoUpdate:   "QSDEV_NO_UPDATE_CHECK",
		EnvPrefix:     "QSDEV_",
		LogFilePrefix: "qsdev-",
		TempPrefix:    ".qsdev-tmp-",
		GitHubOwner:   "Quantum-Serendipity",
		GitHubRepo:    "qsdev",
	}
}

// active holds the current branding. It is initialized with the defaults at
// package initialization, so Get never observes a nil configuration.
var active = newActive()

func newActive() *atomic.Pointer[Config] {
	var p atomic.Pointer[Config]
	d := Default()
	p.Store(&d)
	return &p
}

// Set merges non-empty fields from cfg into the active branding configuration.
// Must be called early in main(), before cmd.Main(): it panics once the gdev
// lifecycle has locked customizations down, so addons can never observe the
// branding change after they captured it. Concurrent calls are safe; each
// merge is applied atomically and none is lost.
func Set(cfg Config) {
	gdevinstance.CheckCanCustomize()
	for {
		old := active.Load()
		next := merged(*old, cfg)
		if active.CompareAndSwap(old, &next) {
			return
		}
	}
}

// merged returns current with every non-empty field of cfg applied.
func merged(current, cfg Config) Config {
	setIfNonEmpty(&current.AppName, cfg.AppName)
	setIfNonEmpty(&current.ConfigFile, cfg.ConfigFile)
	setIfNonEmpty(&current.LocalConfig, cfg.LocalConfig)
	setIfNonEmpty(&current.StateDir, cfg.StateDir)
	setIfNonEmpty(&current.EnvLogVar, cfg.EnvLogVar)
	setIfNonEmpty(&current.EnvLogDirVar, cfg.EnvLogDirVar)
	setIfNonEmpty(&current.EnvNoUpdate, cfg.EnvNoUpdate)
	setIfNonEmpty(&current.EnvPrefix, cfg.EnvPrefix)
	setIfNonEmpty(&current.LogFilePrefix, cfg.LogFilePrefix)
	setIfNonEmpty(&current.TempPrefix, cfg.TempPrefix)
	setIfNonEmpty(&current.GitHubOwner, cfg.GitHubOwner)
	setIfNonEmpty(&current.GitHubRepo, cfg.GitHubRepo)
	return current
}

func setIfNonEmpty(dst *string, v string) {
	if v != "" {
		*dst = v
	}
}

// Get returns the current branding configuration.
func Get() Config {
	return *active.Load()
}

// GeneratedBy returns a standard "Generated by <appname>" attribution string.
func GeneratedBy() string {
	return "Generated by " + Get().AppName
}

// RepoURL returns the GitHub repository URL derived from branding fields.
func RepoURL() string {
	cfg := Get()
	return "https://github.com/" + cfg.GitHubOwner + "/" + cfg.GitHubRepo
}

// InstallScriptURL returns the raw URL to the install script hosted on the
// main branch of the project's GitHub repository.
func InstallScriptURL() string {
	cfg := Get()
	return "https://raw.githubusercontent.com/" + cfg.GitHubOwner + "/" + cfg.GitHubRepo + "/main/install.sh"
}

// ReleaseWorkflowIdentity returns the Sigstore certificate-identity parameters
// used to verify a specific release's artifacts against the EXACT signing
// subject of this project's release workflow. It returns the exact Subject
// Alternative Name (SAN) pinning BOTH the workflow file and the git ref:
//
//	https://github.com/<owner>/<repo>/.github/workflows/release.yml@refs/tags/<tag>
//
// Self-update matches it exactly as the SAN of the signing certificate (the
// in-process sigstore-go equivalent of cosign's --certificate-identity), which
// rejects any signature produced by a different workflow file or on a different
// ref — closing the impersonation gap left by a permissive regexp. issuer is the
// GitHub Actions OIDC token issuer. Owner/repo derive from branding so
// forks/rebrands verify against their own release workflow.
//
// This is qsdev's own identity; it must never be used to verify images or
// artifacts of a project that qsdev initializes.
func ReleaseWorkflowIdentity(tag string) (issuer, identity string) {
	identity = RepoURL() + "/.github/workflows/" + ReleaseWorkflow + "@refs/tags/" + tag
	return GitHubActionsOIDCIssuer, identity
}
