package branding

import (
	"regexp"
	"sync/atomic"
)

// githubActionsOIDCIssuer is the OIDC token issuer for keyless (Sigstore /
// cosign) signatures produced by GitHub Actions workflows.
const githubActionsOIDCIssuer = "https://token.actions.githubusercontent.com"

type Config struct {
	AppName       string
	ConfigFile    string
	LocalConfig   string
	StateDir      string
	EnvLogVar     string
	EnvLogDirVar  string
	EnvNoUpdate   string
	EnvPrefix     string
	LogFilePrefix string
	TempPrefix    string
	GitHubOwner   string
	GitHubRepo    string
}

func Default() Config {
	return Config{
		AppName:       "qsdev",
		ConfigFile:    ".qsdev.yaml",
		LocalConfig:   ".qsdev.local.yaml",
		StateDir:      ".devinit",
		EnvLogVar:     "QSDEV_LOG",
		EnvLogDirVar:  "QSDEV_LOG_DIR",
		EnvNoUpdate:   "QSDEV_NO_UPDATE_CHECK",
		EnvPrefix:     "QSDEV_",
		LogFilePrefix: "qsdev-",
		TempPrefix:    ".qsdev-tmp-",
		GitHubOwner:   "Quantum-Serendipity",
		GitHubRepo:    "qsdev",
	}
}

var active atomic.Pointer[Config]

func init() {
	d := Default()
	active.Store(&d)
}

// Set merges non-empty fields from cfg into the active branding configuration.
// Must be called early in main(), before cmd.Main(). The gdev lockdown lifecycle
// prevents Set from being called after initialization.
func Set(cfg Config) {
	current := *active.Load()
	if cfg.AppName != "" {
		current.AppName = cfg.AppName
	}
	if cfg.ConfigFile != "" {
		current.ConfigFile = cfg.ConfigFile
	}
	if cfg.LocalConfig != "" {
		current.LocalConfig = cfg.LocalConfig
	}
	if cfg.StateDir != "" {
		current.StateDir = cfg.StateDir
	}
	if cfg.EnvLogVar != "" {
		current.EnvLogVar = cfg.EnvLogVar
	}
	if cfg.EnvLogDirVar != "" {
		current.EnvLogDirVar = cfg.EnvLogDirVar
	}
	if cfg.EnvNoUpdate != "" {
		current.EnvNoUpdate = cfg.EnvNoUpdate
	}
	if cfg.EnvPrefix != "" {
		current.EnvPrefix = cfg.EnvPrefix
	}
	if cfg.LogFilePrefix != "" {
		current.LogFilePrefix = cfg.LogFilePrefix
	}
	if cfg.TempPrefix != "" {
		current.TempPrefix = cfg.TempPrefix
	}
	if cfg.GitHubOwner != "" {
		current.GitHubOwner = cfg.GitHubOwner
	}
	if cfg.GitHubRepo != "" {
		current.GitHubRepo = cfg.GitHubRepo
	}
	active.Store(&current)
}

// Get returns the current branding configuration.
func Get() Config {
	return *active.Load()
}

// GeneratedBy returns a standard "Generated by <appname>" attribution string.
func GeneratedBy() string {
	return "Generated by " + Get().AppName
}

// RepoURL returns the GitHub repository URL derived from branding fields.
func RepoURL() string {
	cfg := Get()
	return "https://github.com/" + cfg.GitHubOwner + "/" + cfg.GitHubRepo
}

// InstallScriptURL returns the raw URL to the install script hosted on the
// main branch of the project's GitHub repository.
func InstallScriptURL() string {
	cfg := Get()
	return "https://raw.githubusercontent.com/" + cfg.GitHubOwner + "/" + cfg.GitHubRepo + "/main/install.sh"
}

// WorkflowIdentity returns the Sigstore certificate-identity parameters used to
// verify release artifacts signed by this project's GitHub Actions workflow.
//
// issuer is the GitHub Actions OIDC token issuer. subjectRegExp is an anchored
// regular expression matching the signing subject — any workflow under the
// project's own repository (derived from branding so that forks and rebrands
// verify against their own repository rather than a hardcoded owner/repo). It
// is suitable for cosign's --certificate-identity-regexp flag and can be reused
// by any cosign-based verification policy in this project.
func WorkflowIdentity() (issuer, subjectRegExp string) {
	cfg := Get()
	repo := regexp.QuoteMeta(cfg.GitHubOwner + "/" + cfg.GitHubRepo)
	subjectRegExp = `^https://github\.com/` + repo + `/\.github/workflows/.+$`
	return githubActionsOIDCIssuer, subjectRegExp
}
