package teamreport

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/branding"
)

// GenerateIssues creates GitHub issue specifications for projects with
// critical or high severity alerts. Only one issue is generated per project
// (dedup). Issues include a metric table, issues found, and recommended actions.
func GenerateIssues(report *TeamReport, history *HistoryStore) []IssueSpec {
	// Collect unique projects that have critical or high alerts.
	projectAlerts := make(map[string][]PostureAlert)
	for _, a := range report.Alerts {
		if a.Severity == SeverityCritical || a.Severity == SeverityHigh {
			projectAlerts[a.Project] = append(projectAlerts[a.Project], a)
		}
	}

	if len(projectAlerts) == 0 {
		return nil
	}

	// Walk the projects in report order rather than ranging over the map, so
	// the issues come out in the same order on every run.
	var issues []IssueSpec
	for _, p := range report.Projects {
		alerts, ok := projectAlerts[p.Name]
		if !ok {
			continue
		}
		delete(projectAlerts, p.Name) // one issue per project, even if listed twice

		title := buildIssueTitle(p, history)
		body := buildIssueBody(p, alerts, history)
		labels := []string{"security", branding.Get().AppName + "-posture"}

		issue := IssueSpec{
			Project: p.Name,
			Title:   title,
			Body:    body,
			Repo:    p.Repo,
			Labels:  labels,
		}

		issues = append(issues, issue)
	}

	return issues
}

// buildIssueTitle creates the issue title. If history is available and
// a score delta can be computed, it is included in the title.
func buildIssueTitle(p ProjectSummary, history *HistoryStore) string {
	if history != nil {
		prevScore, ok := history.PreviousScore(p.Name)
		if ok {
			delta := p.Score.Total - prevScore
			if delta != 0 {
				return fmt.Sprintf("[%s] Security posture degraded: %s (%.0f/100, %+.0f)",
					branding.Get().AppName, p.Name, p.Score.Total, delta)
			}
		}
	}

	return fmt.Sprintf("[%s] Security posture degraded: %s (%.0f/100)",
		branding.Get().AppName, p.Name, p.Score.Total)
}

// buildIssueBody constructs the full Markdown body of the issue.
func buildIssueBody(p ProjectSummary, alerts []PostureAlert, history *HistoryStore) string {
	var b strings.Builder

	b.WriteString("## Security Posture Report\n\n")

	// Metric table.
	b.WriteString("| Metric | Value |\n")
	b.WriteString("|--------|-------|\n")
	fmt.Fprintf(&b, "| Score | %.1f/100 (%s) |\n", p.Score.Total, p.Score.Grade)
	fmt.Fprintf(&b, "| Defense Score | %.1f |\n", p.Score.Defense)
	fmt.Fprintf(&b, "| Config Score | %.1f |\n", p.Score.Config)
	fmt.Fprintf(&b, "| Dependency Health | %.1f |\n", p.Score.DepHealth)

	baselineStatus := "PASS"
	if !p.Conformance.Baseline.Pass {
		baselineStatus = "FAIL"
	}
	fmt.Fprintf(&b, "| Baseline Conformance | %s |\n", baselineStatus)

	if p.Scanned {
		fmt.Fprintf(&b, "| Critical Vulnerabilities | %d |\n", p.VulnTotals.Critical)
		fmt.Fprintf(&b, "| High Vulnerabilities | %d |\n", p.VulnTotals.High)
	} else {
		b.WriteString("| Critical Vulnerabilities | n/a (not scanned) |\n")
		b.WriteString("| High Vulnerabilities | n/a (not scanned) |\n")
	}
	fmt.Fprintf(&b, "| %s Version | %s |\n", branding.Get().AppName, p.QsdevVersion)

	if history != nil {
		prevScore, ok := history.PreviousScore(p.Name)
		if ok {
			delta := p.Score.Total - prevScore
			fmt.Fprintf(&b, "| Previous Score | %.1f (%+.1f) |\n", prevScore, delta)
		}
	}

	b.WriteString("\n## Issues Found\n\n")
	for _, a := range alerts {
		fmt.Fprintf(&b, "- **[%s]** %s\n", strings.ToUpper(a.Severity), a.Message)
	}

	b.WriteString("\n## Recommended Actions\n\n")
	seen := make(map[string]bool)
	for _, a := range alerts {
		if !seen[a.Action] {
			fmt.Fprintf(&b, "1. %s\n", a.Action)
			seen[a.Action] = true
		}
	}

	fmt.Fprintf(&b, "\n---\n*Generated by %s team-report*\n", branding.Get().AppName)

	return b.String()
}

// ErrIssueRepoUnknown reports issues that could not be created because the
// project's source repository is unknown (the posture report carried none).
var ErrIssueRepoUnknown = errors.New("repository unknown; issue not created")

// CreateIssuesViaCLI creates GitHub issues using the gh CLI tool, each in its
// project's repository, and returns how many were actually created. Issues
// whose repository is unknown are not silently dropped: they are reported in
// an error wrapping ErrIssueRepoUnknown after the others have been created.
// Cancelling ctx stops before the next issue.
func CreateIssuesViaCLI(ctx context.Context, issues []IssueSpec) (int, error) {
	created := 0
	var unknownRepo []string
	for _, issue := range issues {
		if err := ctx.Err(); err != nil {
			return created, fmt.Errorf("creating issues: %w", err)
		}
		if issue.Repo == "" {
			unknownRepo = append(unknownRepo, issue.Project)
			continue
		}

		args := []string{"issue", "create",
			"--repo", issue.Repo,
			"--title", issue.Title,
			"--body", issue.Body,
		}

		for _, label := range issue.Labels {
			args = append(args, "--label", label)
		}

		output, err := runGH(ctx, args...)
		if err != nil {
			return created, fmt.Errorf("creating issue for %s: %w\noutput: %s", issue.Repo, err, string(output))
		}
		created++
	}

	if len(unknownRepo) > 0 {
		sort.Strings(unknownRepo)
		return created, fmt.Errorf("%w for %d project(s): %s", ErrIssueRepoUnknown,
			len(unknownRepo), strings.Join(unknownRepo, ", "))
	}
	return created, nil
}
