package teamreport

import (
	"fmt"
	"os/exec"
	"strings"
)

// GenerateIssues creates GitHub issue specifications for projects with
// critical or high severity alerts. Only one issue is generated per project
// (dedup). Issues include a metric table, issues found, and recommended actions.
func GenerateIssues(report *TeamReport, history *HistoryStore) []IssueSpec {
	// Collect unique projects that have critical or high alerts.
	projectAlerts := make(map[string][]PostureAlert)
	for _, a := range report.Alerts {
		if a.Severity == SeverityCritical || a.Severity == SeverityHigh {
			projectAlerts[a.Project] = append(projectAlerts[a.Project], a)
		}
	}

	if len(projectAlerts) == 0 {
		return nil
	}

	// Build a lookup of project summaries.
	projectMap := make(map[string]ProjectSummary)
	for _, p := range report.Projects {
		projectMap[p.Name] = p
	}

	var issues []IssueSpec
	for projectName, alerts := range projectAlerts {
		p, ok := projectMap[projectName]
		if !ok {
			continue
		}

		title := buildIssueTitle(p, history)
		body := buildIssueBody(p, alerts, history)
		labels := []string{"security", "gdev-posture"}

		issue := IssueSpec{
			Title:  title,
			Body:   body,
			Repo:   p.Repo,
			Labels: labels,
		}

		issues = append(issues, issue)
	}

	return issues
}

// buildIssueTitle creates the issue title. If history is available and
// a score delta can be computed, it is included in the title.
func buildIssueTitle(p ProjectSummary, history *HistoryStore) string {
	if history != nil {
		prevScore, ok := history.PreviousScore(p.Name)
		if ok {
			delta := p.Score.Total - prevScore
			if delta != 0 {
				return fmt.Sprintf("[gdev] Security posture degraded: %s (%.0f/100, %+.0f)",
					p.Name, p.Score.Total, delta)
			}
		}
	}

	return fmt.Sprintf("[gdev] Security posture degraded: %s (%.0f/100)",
		p.Name, p.Score.Total)
}

// buildIssueBody constructs the full Markdown body of the issue.
func buildIssueBody(p ProjectSummary, alerts []PostureAlert, history *HistoryStore) string {
	var b strings.Builder

	b.WriteString("## Security Posture Report\n\n")

	// Metric table.
	b.WriteString("| Metric | Value |\n")
	b.WriteString("|--------|-------|\n")
	fmt.Fprintf(&b, "| Score | %.1f/100 (%s) |\n", p.Score.Total, p.Score.Grade)
	fmt.Fprintf(&b, "| Defense Score | %.1f |\n", p.Score.Defense)
	fmt.Fprintf(&b, "| Config Score | %.1f |\n", p.Score.Config)
	fmt.Fprintf(&b, "| Dependency Health | %.1f |\n", p.Score.DepHealth)

	baselineStatus := "PASS"
	if !p.Conformance.Baseline.Pass {
		baselineStatus = "FAIL"
	}
	fmt.Fprintf(&b, "| Baseline Conformance | %s |\n", baselineStatus)

	fmt.Fprintf(&b, "| Critical Vulnerabilities | %d |\n", p.VulnTotals.Critical)
	fmt.Fprintf(&b, "| High Vulnerabilities | %d |\n", p.VulnTotals.High)
	fmt.Fprintf(&b, "| gdev Version | %s |\n", p.GdevVersion)

	if history != nil {
		prevScore, ok := history.PreviousScore(p.Name)
		if ok {
			delta := p.Score.Total - prevScore
			fmt.Fprintf(&b, "| Previous Score | %.1f (%+.1f) |\n", prevScore, delta)
		}
	}

	b.WriteString("\n## Issues Found\n\n")
	for _, a := range alerts {
		fmt.Fprintf(&b, "- **[%s]** %s\n", strings.ToUpper(a.Severity), a.Message)
	}

	b.WriteString("\n## Recommended Actions\n\n")
	seen := make(map[string]bool)
	for _, a := range alerts {
		if !seen[a.Action] {
			fmt.Fprintf(&b, "1. %s\n", a.Action)
			seen[a.Action] = true
		}
	}

	b.WriteString("\n---\n*Generated by gdev team-report*\n")

	return b.String()
}

// CreateIssuesViaCLI creates GitHub issues using the gh CLI tool.
// Each issue is created in its corresponding repository.
func CreateIssuesViaCLI(issues []IssueSpec) error {
	for _, issue := range issues {
		if issue.Repo == "" {
			continue
		}

		args := []string{"issue", "create",
			"--repo", issue.Repo,
			"--title", issue.Title,
			"--body", issue.Body,
		}

		for _, label := range issue.Labels {
			args = append(args, "--label", label)
		}

		cmd := exec.Command("gh", args...)
		output, err := cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("creating issue for %s: %w\noutput: %s", issue.Repo, err, string(output))
		}
	}

	return nil
}
