// Package tools aggregates the framework-agnostic MCP tool modules the
// universal server mounts. Each module is a named group of registrations in its
// own sub-package: security/ (credential_vend, security_scan, policy_check),
// devenv/ (env_info, nix_run), status/ (qsdev_status, qsdev_devenv_doctor),
// agentpostmortem/ (session analysis and the verification checklist) and
// versionsentinel/ (dependency versions and drift), with shared helpers in
// toolutil/. Two tools are opt-in (see Options).
//
// `qsdev mcp serve` mounts every module; `qsdev mcp serve --module <name>`
// mounts only the named ones, which is how a client that registers one MCP
// server per module (the catalog's agent-postmortem and version-sentinel
// servers) reaches those tools. Either way the tools run behind the server's
// middleware chain (guardrail, rate limiting, content safety, audit) and are
// governed by the project's mcp.disabled_tools.
//
// Every registration is fully implemented and delegates to real qsdev packages
// or external APIs; none is a stub. Each is tagged with the middleware Category
// that governs its rate limit and content-safety handling.
package tools

import (
	"fmt"
	"slices"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/internal/mcpserve/middleware"
	"github.com/Quantum-Serendipity/qsdev/internal/mcpserve/spi"
	"github.com/Quantum-Serendipity/qsdev/internal/mcpserve/tools/agentpostmortem"
	"github.com/Quantum-Serendipity/qsdev/internal/mcpserve/tools/devenv"
	"github.com/Quantum-Serendipity/qsdev/internal/mcpserve/tools/security"
	"github.com/Quantum-Serendipity/qsdev/internal/mcpserve/tools/status"
	"github.com/Quantum-Serendipity/qsdev/internal/mcpserve/tools/versionsentinel"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// Names of the modules whose sub-packages do not name themselves.
const (
	ModuleSecurity = "security"
	ModuleDevenv   = "devenv"
	ModuleStatus   = "status"
)

// Options selects the opt-in tools All registers. The zero value registers
// neither, so a caller that forgets to set them fails closed.
type Options struct {
	// CredentialVend is the project's security.credential_vend.
	// qsdev_credential_vend is registered only when it is enabled, and vends
	// only what its allow-lists name.
	CredentialVend types.CredentialVendConfig
	// NixRun registers qsdev_nix_run.
	NixRun bool
}

// module is a named group of tool registrations, built only when mounted.
type module struct {
	name  string
	build func(projectRoot string, enforced *middleware.Policy, opts Options) []spi.ToolRegistration
}

// modules returns every tool module in mount order.
func modules() []module {
	return []module{
		{ModuleSecurity, func(root string, enforced *middleware.Policy, opts Options) []spi.ToolRegistration {
			return security.Tools(root, enforced, opts.CredentialVend)
		}},
		{ModuleDevenv, func(root string, _ *middleware.Policy, opts Options) []spi.ToolRegistration {
			return devenv.Tools(root, opts.NixRun)
		}},
		{ModuleStatus, func(root string, _ *middleware.Policy, _ Options) []spi.ToolRegistration {
			return status.Tools(root)
		}},
		{agentpostmortem.ModuleName, func(root string, _ *middleware.Policy, _ Options) []spi.ToolRegistration {
			return agentpostmortem.Tools(root)
		}},
		{versionsentinel.ModuleName, func(root string, _ *middleware.Policy, _ Options) []spi.ToolRegistration {
			return versionsentinel.Tools(root)
		}},
	}
}

// ModuleNames returns the name of every tool module, in mount order.
func ModuleNames() []string {
	all := modules()
	names := make([]string, len(all))
	for i, m := range all {
		names[i] = m.name
	}
	return names
}

// LegacyServerModules returns the modules that older releases served with a
// standalone `qsdev mcp <module>` subcommand outside the middleware chain. A
// .mcp.json generated by such a release still launches that subcommand, so it
// is kept as a hidden alias of `qsdev mcp serve --module <module>`.
func LegacyServerModules() []string {
	return []string{agentpostmortem.ModuleName, versionsentinel.ModuleName}
}

// All returns the registrations of every tool module bound to projectRoot, as
// opts selects the opt-in tools, ready to be mounted on the universal server.
// The order is stable: module by module, in ModuleNames order. enforced is the
// Guardrail policy installed in the server's middleware chain (nil when nothing
// is narrowed); qsdev_policy_check reports from it so "reported enforced" is
// exactly what is enforced.
func All(projectRoot string, enforced *middleware.Policy, opts Options) []spi.ToolRegistration {
	regs, _ := Select(nil, projectRoot, enforced, opts)
	return regs
}

// Select returns the registrations of the named tool modules (every module
// when names is empty), otherwise like All. An unknown module name is an error,
// so a mistyped server definition fails at startup instead of serving nothing.
func Select(names []string, projectRoot string, enforced *middleware.Policy, opts Options) ([]spi.ToolRegistration, error) {
	known := ModuleNames()
	for _, name := range names {
		if !slices.Contains(known, name) {
			return nil, fmt.Errorf("unknown MCP tool module %q: want one of %s", name, strings.Join(known, ", "))
		}
	}
	var regs []spi.ToolRegistration
	for _, m := range modules() {
		if len(names) == 0 || slices.Contains(names, m.name) {
			regs = append(regs, m.build(projectRoot, enforced, opts)...)
		}
	}
	return regs, nil
}

// Names returns the name of every tool All can register, whatever the
// Options, in All's order.
func Names() []string {
	every := Options{CredentialVend: types.CredentialVendConfig{Enabled: true}, NixRun: true}
	regs := All("", nil, every)
	names := make([]string, len(regs))
	for i, r := range regs {
		names[i] = r.Name
	}
	return names
}
