package teardown

import (
	"path"

	"github.com/Quantum-Serendipity/qsdev/internal/answers"
	"github.com/Quantum-Serendipity/qsdev/internal/state"
	"github.com/Quantum-Serendipity/qsdev/internal/toolreg"
	"github.com/Quantum-Serendipity/qsdev/pkg/branding"
	"github.com/Quantum-Serendipity/qsdev/pkg/generate"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// stateFilesForTeardown returns the state file paths that are removed as part
// of the default teardown: every addon state file (from state.StateFilePaths,
// the single source of truth) plus the saved answers, the per-addon answers
// copies, the project config and the committed generated-file manifest.
func stateFilesForTeardown() []string {
	b := branding.Get()
	statePaths := state.StateFilePaths()
	files := make([]string, 0, len(statePaths)+5)
	files = append(files, statePaths[:]...)
	return append(files,
		path.Join(answers.PrimaryDir(), answers.PrimaryFilename()),
		answers.DevenvCopyFile(),
		answers.LegacyClaudeCopyFile(),
		b.ConfigFile,
		state.ManifestFile(),
	)
}

// BuildPlan creates a TeardownPlan from classified files and options.
func BuildPlan(classified []ClassifiedFile, opts TeardownOptions) *TeardownPlan {
	plan := &TeardownPlan{
		Profile: opts.Profile,
		Dirs:    []string{branding.Get().StateDir},
	}

	if opts.Profile == ProfileQuick {
		// Quick profile: only dirs, no file operations.
		return plan
	}

	// Default and Compliance profiles process all classified files.
	for _, cf := range classified {
		if cf.Deleted {
			continue
		}

		// A manual-merge file (devenv.nix) is written whole by qsdev and
		// never merged into a user's file, so its generated sidecar goes too.
		if cf.Strategy == types.ManualMerge {
			plan.Remove = append(plan.Remove, FileAction{
				Path:   cf.Path + generate.SidecarSuffix,
				Reason: "generated sidecar of " + cf.Path,
			})
		}

		switch {
		case cf.Ownership == toolreg.Shared && cf.Strategy == types.ManualMerge && !cf.Modified:
			// Tools add sections to it, but the whole file is qsdev output:
			// removing only the sections would leave a qsdev-specific file.
			plan.Remove = append(plan.Remove, FileAction{
				Path:   cf.Path,
				Reason: "generated by " + branding.Get().AppName + " and unmodified",
			})
		case cf.Ownership == toolreg.Exclusive:
			if cf.Modified {
				plan.Preserve = append(plan.Preserve, FileAction{
					Path:     cf.Path,
					Reason:   "file has been modified by user",
					Modified: true,
				})
			} else {
				plan.Remove = append(plan.Remove, FileAction{
					Path:   cf.Path,
					Reason: "exclusively owned by " + branding.Get().AppName,
				})
			}
		case cf.Ownership == toolreg.Shared:
			plan.Clean = append(plan.Clean, FileAction{
				Path:        cf.Path,
				Reason:      "surgically remove " + branding.Get().AppName + " sections",
				BaseContent: cf.BaseContent,
			})
		}
	}

	// Add state files to the remove list.
	for _, sf := range stateFilesForTeardown() {
		plan.Remove = append(plan.Remove, FileAction{
			Path:   sf,
			Reason: branding.Get().AppName + " state file",
		})
	}

	return plan
}
