package posture

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/Quantum-Serendipity/qsdev/internal/config"
	"github.com/Quantum-Serendipity/qsdev/internal/detect"
	"github.com/Quantum-Serendipity/qsdev/internal/posture/drift"
	"github.com/Quantum-Serendipity/qsdev/internal/state"
	"github.com/Quantum-Serendipity/qsdev/internal/tier"
	"github.com/Quantum-Serendipity/qsdev/internal/version"
	"github.com/Quantum-Serendipity/qsdev/pkg/branding"
	"github.com/Quantum-Serendipity/qsdev/pkg/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// ErrNotInitialized is returned when Assess is called on a project that has
// not been initialized with qsdev init (no state files or .qsdev.yaml found).
var ErrNotInitialized = errors.New("project not initialized: run 'qsdev init' first")

// Assess performs a security posture assessment of the project at projectPath.
// It loads all state files, checks that the project is initialized, and
// assembles a PostureReport. Returns ErrNotInitialized if no state files or
// .qsdev.yaml exist.
func Assess(projectPath string, opts AssessOptions) (*PostureReport, error) {
	// Validate that the project path exists.
	info, err := os.Stat(projectPath)
	if err != nil {
		return nil, fmt.Errorf("accessing project path: %w", err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("project path is not a directory: %s", projectPath)
	}

	// Load all state files.
	merged := LoadAllStates(projectPath)

	// Check for .qsdev.yaml as an alternative initialization indicator.
	qsdevYAMLExists := false
	if _, err := os.Stat(filepath.Join(projectPath, branding.Get().ConfigFile)); err == nil {
		qsdevYAMLExists = true
	}

	// If no state files were loaded and no .qsdev.yaml exists, the project
	// is not initialized.
	if !merged.HasAnyState() && !qsdevYAMLExists {
		return nil, ErrNotInitialized
	}

	// Determine project name from directory basename.
	projectName := filepath.Base(projectPath)

	// Get version info.
	buildInfo := version.Info()
	qsdevVersion := buildInfo.Version
	if merged.QsdevVersion != "" {
		qsdevVersion = merged.QsdevVersion
	}

	report := &PostureReport{
		SchemaVersion: SchemaVersion,
		GeneratedAt:   time.Now().UTC(),
		QsdevVersion:  qsdevVersion,
		ProjectPath:   projectPath,
		ProjectName:   projectName,
		Score: AggregateScore{
			Grade: "U", // Unscored — will be filled by scoring logic.
		},
		Conformance: ConformanceResult{
			Baseline: ConformanceLevel{
				Checks: []ConformanceCheck{},
			},
			Enhanced: ConformanceLevel{
				Checks: []ConformanceCheck{},
			},
		},
		Defense: DefenseCoverage{
			Layers: []DefenseLayer{},
		},
		Config: ConfigHealth{
			Files: []ConfigFileInfo{},
		},
		Dependencies: DependencyHealth{
			Ecosystems: []EcosystemStatus{},
		},
		Drift: drift.Report{
			Categories: []drift.Category{},
			BySeverity: make(map[drift.Severity]int),
		},
		Tools:      []ToolStatus{},
		Ecosystems: []EcosystemStatus{},
	}

	// Determine progressive tier from config.
	currentTierName := "standard"
	configPath := filepath.Join(projectPath, branding.Get().ConfigFile)
	if cfg, cfgErr := config.ParseQsdevConfig(configPath); cfgErr == nil {
		if cfg.Tier != "" {
			currentTierName = cfg.Tier
		} else {
			currentTierName = tier.Infer(cfg.ClaudeCode.PermissionLevel, cfg.ClaudeCode.MCPServers).String()
		}
	}
	nextTierName, _ := tier.NextTier(currentTierName)
	report.Tier = ReportTierInfo{
		Current:  currentTierName,
		Position: tier.Position(currentTierName),
		Total:    tier.Total(),
		NextTier: nextTierName,
	}

	// Record any state loading errors as drift findings.
	for _, loadErr := range merged.Errors {
		report.Drift.Categories = appendOrCreateCategory(
			report.Drift.Categories,
			"state-files",
			drift.Finding{
				Category:    "state-files",
				Severity:    drift.Warning,
				Subject:     loadErr.Path,
				Description: fmt.Sprintf("Failed to load state file: %s", loadErr.Err),
				Remediation: "Re-run 'qsdev init' to regenerate state files.",
				AutoFixable: true,
			},
		)
		report.Drift.TotalFindings++
		report.Drift.BySeverity[drift.Warning]++
	}

	// Build inputs for the scoring pipeline.
	enabledTools := merged.EnabledTools
	genState := types.GeneratedState{
		QsdevVersion: merged.QsdevVersion,
		Files:        merged.Files,
		EnabledTools: merged.EnabledTools,
	}
	detected := detect.Detect(projectPath)

	// Augment genState with filesystem-present config files that may not be
	// in the state (e.g., .pre-commit-config.yaml generated by devenv/nix).
	for _, name := range []string{".pre-commit-config.yaml"} {
		if _, tracked := genState.Files[name]; !tracked {
			if _, err := os.Stat(filepath.Join(projectPath, name)); err == nil {
				genState.Files[name] = types.FileState{}
			}
		}
	}

	// Assess defense layers.
	report.Defense = AssessDefenseLayers(enabledTools, detected, genState, report.Tier.Position)

	// Assess config health from tracked files.
	configFiles := buildConfigFileInfos(projectPath, merged.Files)
	if configFiles == nil {
		configFiles = []ConfigFileInfo{}
	}
	configScore := ComputeConfigScore(configFiles)
	report.Config = ConfigHealth{
		Score: configScore,
		Files: configFiles,
	}
	for _, f := range configFiles {
		report.Config.Total++
		switch f.State {
		case "current":
			report.Config.Current++
		case "modified":
			report.Config.Modified++
		case "outdated":
			report.Config.Outdated++
		case "missing":
			report.Config.Missing++
		}
	}

	// Assess dependency health.
	ecoStatuses := buildEcosystemStatuses(detected, projectPath)
	if ecoStatuses == nil {
		ecoStatuses = []EcosystemStatus{}
	}
	depHealth := ComputeDepScore(ecoStatuses)
	report.Dependencies = depHealth
	if report.Dependencies.Ecosystems == nil {
		report.Dependencies.Ecosystems = []EcosystemStatus{}
	}
	report.Ecosystems = ecoStatuses

	// Evaluate conformance.
	report.Conformance = EvaluateConformance(report.Defense, report.Dependencies, enabledTools, genState)

	// Run drift detection.
	driftReport := drift.Detect(projectPath, genState, enabledTools)
	for _, cat := range driftReport.Categories {
		for _, f := range cat.Findings {
			report.Drift.Categories = appendOrCreateCategory(report.Drift.Categories, cat.Name, f)
			report.Drift.TotalFindings++
			report.Drift.BySeverity[f.Severity]++
		}
	}

	// Compute aggregate score.
	report.Score = ComputeAggregateScore(report.Defense.Score, configScore, report.Dependencies.Score)

	return report, nil
}

// appendOrCreateCategory adds a finding to the named category, creating the
// category if it does not already exist.
func appendOrCreateCategory(categories []drift.Category, name string, finding drift.Finding) []drift.Category {
	for i, cat := range categories {
		if cat.Name == name {
			categories[i].Findings = append(categories[i].Findings, finding)
			return categories
		}
	}
	return append(categories, drift.Category{
		Name:     name,
		Findings: []drift.Finding{finding},
	})
}

// buildConfigFileInfos compares tracked state files against the filesystem
// to determine each file's current health status.
func buildConfigFileInfos(projectPath string, files map[string]types.FileState) []ConfigFileInfo {
	var infos []ConfigFileInfo
	for path, fs := range files {
		info := ConfigFileInfo{
			Path:       path,
			Category:   FileCategory(fs.Strategy),
			StoredHash: fs.Hash,
		}
		absPath := filepath.Join(projectPath, path)
		currentHash, err := state.ComputeFileHash(absPath)
		if err != nil {
			if os.IsNotExist(err) {
				info.State = "missing"
			} else {
				info.State = "corrupt"
			}
		} else {
			info.CurrentHash = currentHash
			info.HashMatch = currentHash == fs.Hash
			if info.HashMatch {
				info.State = "current"
			} else {
				info.State = "modified"
			}
		}
		infos = append(infos, info)
	}
	sort.Slice(infos, func(i, j int) bool { return infos[i].Path < infos[j].Path })
	return infos
}

// buildEcosystemStatuses detects which ecosystems are present and whether
// their lock files exist.
func buildEcosystemStatuses(detected types.DetectedProject, projectPath string) []EcosystemStatus {
	var statuses []EcosystemStatus
	for name, present := range detected.Ecosystems {
		if !present {
			continue
		}
		status := EcosystemStatus{
			Name:     name,
			Detected: true,
		}
		for _, lf := range ecosystem.LockFilesByEcosystem[name] {
			absPath := filepath.Join(projectPath, lf)
			if _, err := os.Stat(absPath); err == nil {
				status.LockFile = lf
				break
			}
		}
		if status.LockFile == "" {
			if _, hasEntries := ecosystem.LockFilesByEcosystem[name]; hasEntries {
				status.LockFile = "missing"
			} else {
				status.LockFile = "n/a"
			}
		}
		statuses = append(statuses, status)
	}
	sort.Slice(statuses, func(i, j int) bool { return statuses[i].Name < statuses[j].Name })
	return statuses
}
