// Package sectools provides security tool configuration generators.
package sectools

import (
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// GenerateGrypeYaml produces a .grype.yaml configuration file for the Grype
// container vulnerability scanner with sensible defaults: fail on high-severity
// vulnerabilities, enable automatic database updates, and set a maximum allowed
// database age.
func GenerateGrypeYaml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# Grype configuration — auto-generated by qsdev\n")
	b.WriteString("# https://github.com/anchore/grype\n\n")
	b.WriteString("fail-on-severity: high\n\n")
	b.WriteString("db:\n")
	b.WriteString("  auto-update: true\n")
	b.WriteString("  max-allowed-built-age: 120h\n")

	return &types.GeneratedFile{
		Path:     ".grype.yaml",
		Content:  []byte(b.String()),
		Mode:     fileutil.ModeReadWrite,
		Strategy: types.Overwrite,
		Owner:    "container-security",
	}, nil
}
