// Package sectools provides security tool configuration generators.
package sectools

import (
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// GenerateGrypeYaml produces a .grype.yaml configuration file for the Grype
// container vulnerability scanner with sensible defaults: fail on high-severity
// vulnerabilities, enable automatic database updates, and set a maximum allowed
// database age.
func GenerateGrypeYaml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# Grype configuration — auto-generated by qsdev\n")
	b.WriteString("# https://github.com/anchore/grype\n\n")
	b.WriteString("fail-on-severity: high\n\n")
	b.WriteString("db:\n")
	b.WriteString("  auto-update: true\n")
	b.WriteString("  max-allowed-built-age: 120h\n")

	return &types.GeneratedFile{
		Path:     ".grype.yaml",
		Content:  []byte(b.String()),
		Mode:     0644,
		Strategy: types.Overwrite,
		Owner:    "container-security",
	}, nil
}

// GenerateCosignPolicy produces a .cosign/policy.yaml file that configures
// keyless OIDC-based container image verification via Sigstore.
func GenerateCosignPolicy(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# Cosign verification policy — auto-generated by qsdev\n")
	b.WriteString("# https://docs.sigstore.dev/policy-controller/overview/\n\n")
	b.WriteString("apiVersion: policy.sigstore.dev/v1beta1\n")
	b.WriteString("kind: ClusterImagePolicy\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: keyless-oidc-verification\n")
	b.WriteString("spec:\n")
	b.WriteString("  images:\n")
	b.WriteString("    - glob: \"**\"\n")
	b.WriteString("  authorities:\n")
	b.WriteString("    - keyless:\n")
	b.WriteString("        url: https://fulcio.sigstore.dev\n")
	b.WriteString("        identities:\n")
	b.WriteString("          - issuerRegExp: \".*\"\n")
	b.WriteString("            subjectRegExp: \".*\"\n")
	b.WriteString("      ctlog:\n")
	b.WriteString("        url: https://rekor.sigstore.dev\n")

	return &types.GeneratedFile{
		Path:     ".cosign/policy.yaml",
		Content:  []byte(b.String()),
		Mode:     0644,
		Strategy: types.Overwrite,
		Owner:    "container-security",
	}, nil
}
