package sectools

import (
	"fmt"
	"net/url"
	"regexp"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/branding"
	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// cosignPolicyPath is where the container-security tool writes the
// policy-controller ClusterImagePolicy.
const cosignPolicyPath = ".cosign/policy.yaml"

// gitHubHost is the only forge whose keyless signing identity and container
// registry path qsdev derives from the origin remote. GitHub Enterprise Server
// uses a different OIDC issuer per instance, so it gets the template.
const gitHubHost = "github.com"

var (
	gitHubOwnerPattern = regexp.MustCompile(`^[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?$`)
	gitHubRepoPattern  = regexp.MustCompile(`^[A-Za-z0-9._-]+$`)
	// nonDNSLabel matches runs of characters outside an RFC 1123 DNS label.
	// Dots are replaced too: a subdomain with a label that ends in "-" or is
	// empty ("a-.b", "a..b") is not a valid Kubernetes object name.
	nonDNSLabel = regexp.MustCompile(`[^a-z0-9]+`)
)

// gitHubRepo identifies a repository on github.com.
type gitHubRepo struct {
	owner string
	name  string
}

// GenerateCosignPolicy produces a .cosign/policy.yaml ClusterImagePolicy for
// the Sigstore policy-controller.
//
// When the project's origin remote is a github.com repository, the policy is
// scoped to that repository's GHCR image path and accepts only images
// keyless-signed by a GitHub Actions workflow in that same repository. Any
// other remote (or none) yields a fully commented-out template with TODO
// placeholders: qsdev cannot know the registry path or signing identity, and
// an enforcing policy with a guessed identity would reject every image.
//
// The file uses the manual-merge strategy: once a user fills in the template
// or adds policies of their own, a regenerated version is written beside it
// instead of over it.
func GenerateCosignPolicy(a types.WizardAnswers) (*types.GeneratedFile, error) {
	var content string
	if repo, ok := parseGitHubRemote(a.Detected.RemoteURL); ok {
		content = cosignPolicyForGitHub(repo)
	} else {
		content = cosignPolicyTemplate(a.Detected.RemoteURL != "")
	}
	return &types.GeneratedFile{
		Path:     cosignPolicyPath,
		Content:  []byte(content),
		Mode:     fileutil.ModeReadWrite,
		Strategy: types.ManualMerge,
		Owner:    "container-security",
	}, nil
}

// cosignPolicyForGitHub renders an enforcing policy pinned to repo: its images
// are the ones published under ghcr.io/<owner>/<repo>, and its signing subject
// is any workflow in that repository.
func cosignPolicyForGitHub(repo gitHubRepo) string {
	// GHCR image names are always lowercase.
	image := "ghcr.io/" + strings.ToLower(repo.owner+"/"+repo.name)
	// GitHub owner and repository names are case-insensitive, and the
	// certificate carries GitHub's canonical casing, which the remote URL
	// need not match. Matching case-insensitively admits no other repository.
	subjectRegExp := "(?i)^" + regexp.QuoteMeta("https://"+gitHubHost+"/"+repo.owner+"/"+repo.name+"/.github/workflows/") + ".+$"

	var b strings.Builder
	b.WriteString("# Cosign verification policy — auto-generated by qsdev\n")
	b.WriteString("# https://docs.sigstore.dev/policy-controller/overview/\n")
	b.WriteString("#\n")
	b.WriteString("# Derived from the git origin remote. This policy applies only to images\n")
	fmt.Fprintf(&b, "# published under %s and admits them only when they are keyless-signed\n", image)
	fmt.Fprintf(&b, "# by a GitHub Actions workflow in %s/%s/%s.\n", gitHubHost, repo.owner, repo.name)
	b.WriteString("# If you publish images to another registry, change spec.images.\n")
	b.WriteString("#\n")
	b.WriteString("# Images outside that path (third-party base images, other registries) are\n")
	b.WriteString("# not covered here; the policy-controller's no-match-policy decides whether\n")
	b.WriteString("# they are admitted. Add a ClusterImagePolicy for each source you trust.\n\n")
	b.WriteString("apiVersion: policy.sigstore.dev/v1beta1\n")
	b.WriteString("kind: ClusterImagePolicy\n")
	b.WriteString("metadata:\n")
	fmt.Fprintf(&b, "  name: %s\n", cosignPolicyName(repo))
	b.WriteString("spec:\n")
	b.WriteString("  images:\n")
	fmt.Fprintf(&b, "    - glob: %q\n", image)
	fmt.Fprintf(&b, "    - glob: %q\n", image+"/**")
	b.WriteString("  authorities:\n")
	b.WriteString("    - keyless:\n")
	b.WriteString("        url: https://fulcio.sigstore.dev\n")
	b.WriteString("        identities:\n")
	fmt.Fprintf(&b, "          - issuer: %q\n", branding.GitHubActionsOIDCIssuer)
	fmt.Fprintf(&b, "            subjectRegExp: %q\n", subjectRegExp)
	b.WriteString("      ctlog:\n")
	b.WriteString("        url: https://rekor.sigstore.dev\n")
	return b.String()
}

// cosignPolicyTemplate renders a non-enforcing template: every line of the
// policy is commented out, so applying the file as-is creates nothing.
func cosignPolicyTemplate(hasRemote bool) string {
	reason := "no git origin remote was detected"
	if hasRemote {
		reason = "the git origin remote is not a " + gitHubHost + " repository"
	}

	var b strings.Builder
	b.WriteString("# Cosign verification policy TEMPLATE — auto-generated by qsdev\n")
	b.WriteString("# https://docs.sigstore.dev/policy-controller/overview/\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# NOT ENFORCING: %s, so qsdev cannot tell\n", reason)
	b.WriteString("# where your images are published or which CI identity signs them. The\n")
	b.WriteString("# policy below is commented out; applying this file as-is does nothing.\n")
	b.WriteString("#\n")
	b.WriteString("# To enforce it, uncomment the policy and replace every TODO placeholder.\n")
	b.WriteString("# Signing identities per CI provider:\n")
	b.WriteString("#   https://docs.sigstore.dev/certificate_authority/oidc-in-fulcio/\n")
	b.WriteString("# For GitHub Actions the issuer is " + branding.GitHubActionsOIDCIssuer + "\n")
	b.WriteString("# and the subject is https://github.com/OWNER/REPO/.github/workflows/<file>@<ref>.\n")
	b.WriteString("#\n")
	b.WriteString("# apiVersion: policy.sigstore.dev/v1beta1\n")
	b.WriteString("# kind: ClusterImagePolicy\n")
	b.WriteString("# metadata:\n")
	b.WriteString("#   name: TODO-project-keyless\n")
	b.WriteString("# spec:\n")
	b.WriteString("#   images:\n")
	b.WriteString("#     # TODO: your project's image repository, e.g. registry.example.com/team/app\n")
	b.WriteString("#     - glob: \"TODO-REGISTRY/TODO-NAMESPACE/TODO-IMAGE\"\n")
	b.WriteString("#     - glob: \"TODO-REGISTRY/TODO-NAMESPACE/TODO-IMAGE/**\"\n")
	b.WriteString("#   authorities:\n")
	b.WriteString("#     - keyless:\n")
	b.WriteString("#         url: https://fulcio.sigstore.dev\n")
	b.WriteString("#         identities:\n")
	b.WriteString("#           # TODO: the OIDC issuer and anchored signing-subject regexp of the\n")
	b.WriteString("#           # CI job that signs your images\n")
	b.WriteString("#           - issuer: \"TODO-OIDC-ISSUER\"\n")
	b.WriteString("#             subjectRegExp: \"TODO-SIGNING-SUBJECT-REGEXP\"\n")
	b.WriteString("#       ctlog:\n")
	b.WriteString("#         url: https://rekor.sigstore.dev\n")
	return b.String()
}

// cosignPolicyName returns a Kubernetes object name unique to repo, so
// several projects' policies can coexist in one cluster.
func cosignPolicyName(repo gitHubRepo) string {
	base := nonDNSLabel.ReplaceAllString(strings.ToLower(repo.owner+"-"+repo.name), "-")
	return strings.Trim(base, "-") + "-keyless"
}

// parseGitHubRemote extracts the owner and repository from a github.com git
// remote URL. It accepts URL forms (https://, ssh://, git://, with an optional
// user, port, ".git" suffix and trailing slash) and the scp-like form
// ([user@]github.com:owner/repo.git). Any other host, a path that is not
// exactly owner/repo, or names GitHub would not allow yield ok == false.
func parseGitHubRemote(raw string) (gitHubRepo, bool) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return gitHubRepo{}, false
	}

	var host, path string
	if strings.Contains(raw, "://") {
		u, err := url.Parse(raw)
		if err != nil {
			return gitHubRepo{}, false
		}
		host, path = u.Hostname(), u.Path
	} else {
		authority, p, ok := strings.Cut(raw, ":")
		if !ok {
			return gitHubRepo{}, false
		}
		if at := strings.LastIndex(authority, "@"); at >= 0 {
			authority = authority[at+1:]
		}
		host, path = authority, p
	}
	if !strings.EqualFold(host, gitHubHost) {
		return gitHubRepo{}, false
	}

	path = strings.TrimSuffix(strings.Trim(path, "/"), ".git")
	owner, name, ok := strings.Cut(path, "/")
	if !ok || !gitHubOwnerPattern.MatchString(owner) || !gitHubRepoPattern.MatchString(name) ||
		name == "." || name == ".." {
		return gitHubRepo{}, false
	}
	return gitHubRepo{owner: owner, name: name}, true
}
