// Package sectools provides security tool configuration generators.
package sectools

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// gitleaksAllowPaths returns paths excluded from Gitleaks secret scanning.
// It reuses defaultScanExcludes for entries shared with other scanners,
// keeping this list for gitleaks-only additions (currently none).
func gitleaksAllowPaths() []string {
	// All gitleaks excludes are covered by defaultScanExcludes.
	// Filter to the subset relevant for secret scanning.
	relevant := map[string]bool{
		"vendor/":       true,
		"node_modules/": true,
		".devenv/":      true,
		"testdata/":     true,
	}
	var paths []string
	for _, p := range defaultScanExcludes {
		if relevant[p] {
			paths = append(paths, p)
		}
	}
	return paths
}

// gitleaksPathRegex converts a directory exclude such as "vendor/" into the
// regular expression Gitleaks expects in allowlist paths. The pattern is
// anchored to a path-segment boundary so "vendor/" does not also allowlist
// "myvendor/", and regex metacharacters (the "." in ".devenv/") are escaped.
func gitleaksPathRegex(dir string) string {
	return `(^|/)` + regexp.QuoteMeta(dir)
}

// GenerateGitleaksToml produces a .gitleaks.toml configuration file with a
// default allowlist of paths that are typically safe to exclude from secret
// scanning.
//
// A repo-root .gitleaks.toml replaces Gitleaks' built-in configuration, so the
// file must opt back into the default rule set with [extend] useDefault = true.
// Without it the effective rule set is empty and every scan reports no leaks.
func GenerateGitleaksToml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# Gitleaks configuration — auto-generated by qsdev\n")
	b.WriteString("# https://github.com/gitleaks/gitleaks\n\n")
	b.WriteString("title = \"gitleaks config\"\n\n")
	b.WriteString("# Keep Gitleaks' built-in detection rules; this file only adds an allowlist.\n")
	b.WriteString("[extend]\n")
	b.WriteString("  useDefault = true\n\n")
	b.WriteString("[allowlist]\n")
	b.WriteString("  description = \"Allowlisted paths and patterns\"\n")
	b.WriteString("  regexes = []\n")
	b.WriteString("  paths = [\n")
	for _, p := range gitleaksAllowPaths() {
		// TOML literal strings keep regex backslashes verbatim.
		fmt.Fprintf(&b, "    '''%s''',\n", gitleaksPathRegex(p))
	}
	b.WriteString("  ]\n")

	return &types.GeneratedFile{
		Path:     ".gitleaks.toml",
		Content:  []byte(b.String()),
		Mode:     fileutil.ModeReadWrite,
		Strategy: types.Overwrite,
		Owner:    "gitleaks",
	}, nil
}
