// Package sectools provides security tool configuration generators.
package sectools

import (
	"fmt"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// gitleaksAllowPaths returns paths excluded from Gitleaks secret scanning.
// It reuses defaultScanExcludes for entries shared with other scanners,
// keeping this list for gitleaks-only additions (currently none).
func gitleaksAllowPaths() []string {
	// All gitleaks excludes are covered by defaultScanExcludes.
	// Filter to the subset relevant for secret scanning.
	relevant := map[string]bool{
		"vendor/":       true,
		"node_modules/": true,
		".devenv/":      true,
		"testdata/":     true,
	}
	var paths []string
	for _, p := range defaultScanExcludes {
		if relevant[p] {
			paths = append(paths, p)
		}
	}
	return paths
}

// GenerateGitleaksToml produces a .gitleaks.toml configuration file with a
// default allowlist of paths that are typically safe to exclude from secret
// scanning.
func GenerateGitleaksToml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# Gitleaks configuration — auto-generated by qsdev\n")
	b.WriteString("# https://github.com/gitleaks/gitleaks\n\n")
	b.WriteString("title = \"gitleaks config\"\n\n")
	b.WriteString("[allowlist]\n")
	b.WriteString("  description = \"Allowlisted paths and patterns\"\n")
	b.WriteString("  regexes = []\n")
	b.WriteString("  paths = [\n")
	for _, p := range gitleaksAllowPaths() {
		fmt.Fprintf(&b, "    %q,\n", p)
	}
	b.WriteString("  ]\n")

	return &types.GeneratedFile{
		Path:     ".gitleaks.toml",
		Content:  []byte(b.String()),
		Mode:     0o644,
		Strategy: types.Overwrite,
		Owner:    "gitleaks",
	}, nil
}
