// Package sectools provides security tool configuration generators.
package sectools

import (
	"fmt"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// defaultGitleaksAllowPaths lists paths excluded from Gitleaks secret scanning.
var defaultGitleaksAllowPaths = []string{
	"vendor/",
	"node_modules/",
	".devenv/",
	"docs/",
	"testdata/",
}

// GenerateGitleaksToml produces a .gitleaks.toml configuration file with a
// default allowlist of paths that are typically safe to exclude from secret
// scanning.
func GenerateGitleaksToml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# Gitleaks configuration — auto-generated by qsdev\n")
	b.WriteString("# https://github.com/gitleaks/gitleaks\n\n")
	b.WriteString("title = \"gitleaks config\"\n\n")
	b.WriteString("[allowlist]\n")
	b.WriteString("  description = \"Allowlisted paths and patterns\"\n")
	b.WriteString("  regexes = []\n")
	b.WriteString("  paths = [\n")
	for _, p := range defaultGitleaksAllowPaths {
		fmt.Fprintf(&b, "    %q,\n", p)
	}
	b.WriteString("  ]\n")

	return &types.GeneratedFile{
		Path:     ".gitleaks.toml",
		Content:  []byte(b.String()),
		Mode:     0644,
		Strategy: types.Overwrite,
		Owner:    "gitleaks",
	}, nil
}
