// Package sectools provides security tool configuration generators.
package sectools

import (
	"fmt"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// policyLicense is one license in the ScanCode license policy.
type policyLicense struct {
	spdx string // SPDX identifier, reported in scan findings
	key  string // ScanCode license key, which --license-policy matches on
}

// licensePolicyClass groups the licenses that share a policy outcome. The
// label and compliance_alert follow the ScanCode.io policy convention: an
// empty alert approves the license, "warning" asks for review and "error"
// prohibits it. The security-scan task fails on "error" only.
type licensePolicyClass struct {
	label    string
	alert    string
	licenses []policyLicense
}

// licensePolicy is the generated policy. Keys were checked against the
// ScanCode LicenseDB (https://scancode-licensedb.aboutcode.org/). ScanCode
// resolves deprecated SPDX identifiers onto the same keys (GPL-2.0 and
// GPL-2.0-only to gpl-2.0, GPL-2.0+ and GPL-2.0-or-later to gpl-2.0-plus), so
// listing each -only and -or-later key covers the legacy spellings too.
var licensePolicy = []licensePolicyClass{
	{
		label: "Approved License",
		alert: "",
		licenses: []policyLicense{
			{"MIT", "mit"},
			{"Apache-2.0", "apache-2.0"},
			{"BSD-2-Clause", "bsd-simplified"},
			{"BSD-3-Clause", "bsd-new"},
			{"ISC", "isc"},
			{"0BSD", "bsd-zero"},
			{"Unlicense", "unlicense"},
			{"CC0-1.0", "cc0-1.0"},
		},
	},
	{
		label: "Restricted License",
		alert: "warning",
		licenses: []policyLicense{
			{"LGPL-2.0-only", "lgpl-2.0"},
			{"LGPL-2.0-or-later", "lgpl-2.0-plus"},
			{"LGPL-2.1-only", "lgpl-2.1"},
			{"LGPL-2.1-or-later", "lgpl-2.1-plus"},
			{"LGPL-3.0-only", "lgpl-3.0"},
			{"LGPL-3.0-or-later", "lgpl-3.0-plus"},
			{"MPL-1.1", "mpl-1.1"},
			{"MPL-2.0", "mpl-2.0"},
			{"EPL-1.0", "epl-1.0"},
			{"EPL-2.0", "epl-2.0"},
			{"CDDL-1.0", "cddl-1.0"},
			{"CDDL-1.1", "cddl-1.1"},
			{"Artistic-2.0", "artistic-2.0"},
		},
	},
	{
		label: "Prohibited License",
		alert: "error",
		licenses: []policyLicense{
			{"GPL-1.0-only", "gpl-1.0"},
			{"GPL-1.0-or-later", "gpl-1.0-plus"},
			{"GPL-2.0-only", "gpl-2.0"},
			{"GPL-2.0-or-later", "gpl-2.0-plus"},
			{"GPL-3.0-only", "gpl-3.0"},
			{"GPL-3.0-or-later", "gpl-3.0-plus"},
			{"AGPL-1.0-only", "agpl-1.0"},
			{"AGPL-1.0-or-later", "agpl-1.0-plus"},
			{"AGPL-3.0-only", "agpl-3.0"},
			{"AGPL-3.0-or-later", "agpl-3.0-plus"},
			{"SSPL-1.0", "mongodb-sspl-1.0"},
			{"BUSL-1.1", "bsl-1.1"},
		},
	},
}

// GenerateScancodeYml produces the ScanCode license policy file
// (ecosystem.LicensePolicyPath) in the format `scancode --license-policy`
// reads: a license_policies list keyed by ScanCode license key, each entry
// carrying a label and a compliance_alert. ScanCode copies the matching
// entries onto every scanned file as its license_policy, and the
// security-scan task fails when any of them has compliance_alert "error".
// Each entry also records its SPDX identifier so findings name the license
// in SPDX terms. Paths to skip are passed on the scan command line, since the
// policy format has no place for them.
func GenerateScancodeYml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# ScanCode license policy — auto-generated by qsdev\n")
	b.WriteString("# The qsdev-security-scan task applies it with\n")
	fmt.Fprintf(&b, "#   scancode --license --license-policy %s ...\n", ecosystem.LicensePolicyPath)
	b.WriteString("# and fails when a scanned file has a license whose compliance_alert is\n")
	b.WriteString("# \"error\"; \"warning\" licenses are listed for manual review.\n")
	b.WriteString("# license_key values are ScanCode license keys:\n")
	b.WriteString("# https://scancode-licensedb.aboutcode.org/\n")
	b.WriteString("# The allowlist pragmas stop ripsecrets from mistaking SPDX ids such as\n")
	b.WriteString("# GPL-3.0-or-later for secrets, which would block committing this file.\n\n")

	b.WriteString("license_policies:\n")
	for _, class := range licensePolicy {
		for _, l := range class.licenses {
			fmt.Fprintf(&b, "  - license_key: %s\n", l.key)
			fmt.Fprintf(&b, "    spdx_license_key: %s # pragma: allowlist secret\n", l.spdx)
			fmt.Fprintf(&b, "    label: %s\n", class.label)
			fmt.Fprintf(&b, "    compliance_alert: '%s'\n", class.alert)
		}
	}

	return &types.GeneratedFile{
		Path:     ecosystem.LicensePolicyPath,
		Content:  []byte(b.String()),
		Mode:     fileutil.ModeReadWrite,
		Strategy: types.Overwrite,
		Owner:    "license-compliance",
	}, nil
}

// GenerateLicenseExceptionsYml produces a .license-exceptions.yml template with
// an empty exceptions list. It uses the Skip strategy so that user-added
// exceptions are preserved across re-runs.
func GenerateLicenseExceptionsYml() (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# License exceptions — edit this file to record approved exceptions\n")
	b.WriteString("# Each entry should document the package, license, and justification.\n")
	b.WriteString("# This is a review record: the qsdev-security-scan license check does not\n")
	b.WriteString("# read it, and the scan skips this file.\n\n")
	b.WriteString("exceptions: []\n")
	b.WriteString("# Example:\n")
	b.WriteString("# exceptions:\n")
	b.WriteString("#   - package: example-pkg\n")
	b.WriteString("#     license: LGPL-2.1-only\n")
	b.WriteString("#     justification: Dynamic linking only, no modifications\n")
	b.WriteString("#     approved_by: security-team\n")
	b.WriteString("#     approved_date: 2025-01-01\n")

	return &types.GeneratedFile{
		Path:     ecosystem.LicenseExceptionsPath,
		Content:  []byte(b.String()),
		Mode:     fileutil.ModeReadWrite,
		Strategy: types.Skip,
		Owner:    "license-compliance",
	}, nil
}
