// Package sectools provides security tool configuration generators.
package sectools

import (
	"fmt"
	"strings"

	"github.com/Quantum-Serendipity/gdev-secure-devenv-bootstrap/pkg/types"
)

// allowedSPDX lists SPDX license identifiers that are permitted without review.
var allowedSPDX = []string{
	"MIT",
	"Apache-2.0",
	"BSD-2-Clause",
	"BSD-3-Clause",
	"ISC",
	"0BSD",
	"Unlicense",
	"CC0-1.0",
}

// blockedSPDX lists SPDX license identifiers that are always rejected.
var blockedSPDX = []string{
	"GPL-2.0-only",
	"GPL-3.0-only",
	"AGPL-3.0-only",
	"SSPL-1.0",
	"BUSL-1.1",
}

// reviewSPDX lists SPDX license identifiers that require manual review.
var reviewSPDX = []string{
	"LGPL-2.1-only",
	"LGPL-3.0-only",
	"MPL-2.0",
	"EPL-2.0",
	"CDDL-1.0",
	"Artistic-2.0",
}

// scancodeExcludePaths lists paths excluded from license scanning.
var scancodeExcludePaths = []string{
	"vendor/",
	"node_modules/",
	".devenv/",
	"dist/",
	"testdata/",
}

// GenerateScancodeYml produces a .scancode.yml configuration file with
// allowed, blocked, and review SPDX license identifiers and path exclusions.
func GenerateScancodeYml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# ScanCode license compliance policy — auto-generated by qsdev\n")
	b.WriteString("# https://scancode-toolkit.readthedocs.io/\n\n")

	b.WriteString("allowed:\n")
	for _, id := range allowedSPDX {
		fmt.Fprintf(&b, "  - %s\n", id)
	}

	b.WriteString("\nblocked:\n")
	for _, id := range blockedSPDX {
		fmt.Fprintf(&b, "  - %s\n", id)
	}

	b.WriteString("\nreview:\n")
	for _, id := range reviewSPDX {
		fmt.Fprintf(&b, "  - %s\n", id)
	}

	b.WriteString("\npaths:\n")
	b.WriteString("  exclude:\n")
	for _, p := range scancodeExcludePaths {
		fmt.Fprintf(&b, "    - %s\n", p)
	}

	return &types.GeneratedFile{
		Path:     ".scancode.yml",
		Content:  []byte(b.String()),
		Mode:     0644,
		Strategy: types.Overwrite,
		Owner:    "license-compliance",
	}, nil
}

// GenerateLicenseExceptionsYml produces a .license-exceptions.yml template with
// an empty exceptions list. It uses the Skip strategy so that user-added
// exceptions are preserved across re-runs.
func GenerateLicenseExceptionsYml() (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# License exceptions — edit this file to record approved exceptions\n")
	b.WriteString("# Each entry should document the package, license, and justification.\n\n")
	b.WriteString("exceptions: []\n")
	b.WriteString("# Example:\n")
	b.WriteString("# exceptions:\n")
	b.WriteString("#   - package: example-pkg\n")
	b.WriteString("#     license: LGPL-2.1-only\n")
	b.WriteString("#     justification: Dynamic linking only, no modifications\n")
	b.WriteString("#     approved_by: security-team\n")
	b.WriteString("#     approved_date: 2025-01-01\n")

	return &types.GeneratedFile{
		Path:     ".license-exceptions.yml",
		Content:  []byte(b.String()),
		Mode:     0644,
		Strategy: types.Skip,
		Owner:    "license-compliance",
	}, nil
}
