package sectools

import (
	"fmt"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

var defaultOpengrepExcludes = []string{
	"vendor/",
	"node_modules/",
	"third_party/",
	"dist/",
	"build/",
	"out/",
	"target/",
	".next/",
	".nuxt/",
	".devenv/",
	".direnv/",
	"result",
	"__pycache__/",
	".venv/",
	"venv/",
	".tox/",
	".egg-info/",
	".cache/",
	".pytest_cache/",
	"coverage/",
	".coverage/",
	"testdata/",
	"fixtures/",
}

// GenerateOpengrepConfigYaml produces a .opengrep/config.yaml configuration
// file. It specifies rule paths, path exclusions, severity threshold, and
// timeout for OpenGrep scans.
func GenerateOpengrepConfigYaml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# OpenGrep configuration — auto-generated by qsdev\n")
	b.WriteString("# https://github.com/opengrep/opengrep\n")
	b.WriteString("rules:\n")
	b.WriteString("  - rules/core\n")
	b.WriteString("\nexclude:\n")
	for _, p := range defaultOpengrepExcludes {
		fmt.Fprintf(&b, "  - %s\n", p)
	}
	b.WriteString("\nseverity: warning\n")
	b.WriteString("timeout: 300\n")

	return &types.GeneratedFile{
		Path:     ".opengrep/config.yaml",
		Content:  []byte(b.String()),
		Mode:     0o644,
		Strategy: types.Overwrite,
		Owner:    "opengrep",
	}, nil
}
