package sectools

import (
	"fmt"
	"path"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
	"github.com/Quantum-Serendipity/qsdev/rules"
)

// opengrepRulesDir is the project-relative directory into which the embedded
// core rule library is delivered. The generated config points OpenGrep here, so
// the rules the config references actually exist in the user's project. It lives
// under the opengrep-owned .opengrep/ directory so the whole footprint is
// contained and managed by enable/update/teardown.
const opengrepRulesDir = ".opengrep/rules/core"

// GenerateOpengrepConfigYaml produces a .opengrep/config.yaml configuration
// file. It specifies rule paths, path exclusions, severity threshold, and
// timeout for OpenGrep scans. The rules path points at opengrepRulesDir, where
// GenerateOpengrepFiles delivers the embedded core rule library.
func GenerateOpengrepConfigYaml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# OpenGrep configuration — auto-generated by qsdev\n")
	b.WriteString("# https://github.com/opengrep/opengrep\n")
	b.WriteString("rules:\n")
	fmt.Fprintf(&b, "  - %s\n", opengrepRulesDir)
	b.WriteString("\nexclude:\n")
	for _, p := range defaultScanExcludes {
		fmt.Fprintf(&b, "  - %s\n", p)
	}
	b.WriteString("\nseverity: warning\n")
	b.WriteString("timeout: 300\n")

	return &types.GeneratedFile{
		Path:     ".opengrep/config.yaml",
		Content:  []byte(b.String()),
		Mode:     fileutil.ModeReadWrite,
		Strategy: types.Overwrite,
		Owner:    "opengrep",
	}, nil
}

// GenerateOpengrepFiles produces the full set of files delivered when the
// opengrep tool is enabled: the .opengrep/config.yaml config plus the embedded
// core taint-rule library, written under opengrepRulesDir so that the path the
// config references actually exists in the user's project.
func GenerateOpengrepFiles(a types.WizardAnswers) ([]types.GeneratedFile, error) {
	cfg, err := GenerateOpengrepConfigYaml(a)
	if err != nil {
		return nil, err
	}
	files := []types.GeneratedFile{*cfg}

	ruleFiles, err := rules.CoreRuleFiles()
	if err != nil {
		return nil, fmt.Errorf("loading embedded opengrep rules: %w", err)
	}
	for _, rf := range ruleFiles {
		files = append(files, types.GeneratedFile{
			Path:     path.Join(opengrepRulesDir, rf.RelPath),
			Content:  rf.Content,
			Mode:     fileutil.ModeReadWrite,
			Strategy: types.Overwrite,
			Owner:    "opengrep",
		})
	}
	return files, nil
}
