package sectools

import (
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// GenerateSyftYaml produces a .syft.yaml configuration file for the Syft
// SBOM generator with sensible defaults: SPDX-JSON output format and
// all-layers cataloging scope.
func GenerateSyftYaml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# Syft configuration — auto-generated by qsdev\n")
	b.WriteString("# https://github.com/anchore/syft\n\n")
	b.WriteString("output:\n")
	b.WriteString("  - \"spdx-json\"\n\n")
	b.WriteString("catalogers:\n")
	b.WriteString("  default:\n")
	b.WriteString("    scope: all-layers\n")

	return &types.GeneratedFile{
		Path:     ".syft.yaml",
		Content:  []byte(b.String()),
		Mode:     0o644,
		Strategy: types.Overwrite,
		Owner:    "container-security",
	}, nil
}
