// Package sectools provides security tool configuration generators for the
// qsdev system. Each generator produces a GeneratedFile
// ready for the file-writing pipeline.
package sectools

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/internal/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// defaultSemgrepExcludes lists paths excluded from Semgrep scanning.
var defaultSemgrepExcludes = []string{
	"vendor/",
	"node_modules/",
	"dist/",
	".devenv/",
}

// GenerateSemgrepYml produces a .semgrep.yml configuration file. It collects
// rule sets from all ecosystem modules implementing SASTModule, deduplicates
// them, and generates a YAML configuration with path exclusions.
func GenerateSemgrepYml(answers types.WizardAnswers, registry *ecosystem.Registry) (*types.GeneratedFile, error) {
	if registry == nil {
		return nil, fmt.Errorf("ecosystem registry must not be nil")
	}

	ruleSets := collectRuleSets(answers, registry)
	if len(ruleSets) == 0 {
		// No SAST-capable modules detected; still produce a minimal config.
		ruleSets = []string{"p/owasp-top-ten"}
	}

	var b strings.Builder
	b.WriteString("# Semgrep configuration — auto-generated by qsdev\n")
	b.WriteString("# https://semgrep.dev/docs/running-rules/\n")
	b.WriteString("rules:\n")
	for _, rs := range ruleSets {
		fmt.Fprintf(&b, "  - %s\n", rs)
	}
	b.WriteString("\npaths:\n")
	b.WriteString("  exclude:\n")
	for _, p := range defaultSemgrepExcludes {
		fmt.Fprintf(&b, "    - %s\n", p)
	}

	return &types.GeneratedFile{
		Path:     ".semgrep.yml",
		Content:  []byte(b.String()),
		Mode:     0644,
		Strategy: types.Overwrite,
		Owner:    "semgrep",
	}, nil
}

// collectRuleSets gathers and deduplicates Semgrep rule sets from ecosystem
// modules that implement the SASTModule interface, filtered to only those
// ecosystems present in the wizard answers.
func collectRuleSets(answers types.WizardAnswers, registry *ecosystem.Registry) []string {
	selected := make(map[string]bool, len(answers.Languages))
	for _, lang := range answers.Languages {
		selected[lang.Name] = true
	}

	seen := make(map[string]bool)
	var ruleSets []string

	for _, mod := range registry.All() {
		if !selected[mod.Name()] {
			continue
		}
		sast, ok := mod.(ecosystem.SASTModule)
		if !ok {
			continue
		}
		for _, rs := range sast.SemgrepRuleSets() {
			if !seen[rs] {
				seen[rs] = true
				ruleSets = append(ruleSets, rs)
			}
		}
	}

	// Sort for deterministic output.
	sort.Strings(ruleSets)
	return ruleSets
}
