// Package sectools provides security tool configuration generators for the
// qsdev system. Each generator produces a GeneratedFile
// ready for the file-writing pipeline.
package sectools

import (
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// SemgrepIgnorePath is the project-relative path of the Semgrep ignore file.
// Semgrep reads it from the scan root, so the security-scan task's
// `semgrep ... .` honours it without extra flags.
const SemgrepIgnorePath = ".semgrepignore"

// GenerateSemgrepIgnore produces the .semgrepignore file holding the default
// scan exclusions, in the gitignore syntax Semgrep expects.
//
// Semgrep has no project config file that selects registry rule packs or path
// exclusions: a config file may only contain rule objects. The rule packs the
// selected ecosystems declare (SASTModule) are therefore passed by the
// security-scan task as --config flags, together with the project's own rules
// in ecosystem.SemgrepLocalRulesDir, and the exclusions live here.
//
// A .semgrepignore replaces Semgrep's built-in default ignore list, so every
// default exclusion the project needs must be listed. The project's own rules
// directory is excluded too: its rule files are --config inputs, and scanned
// as targets a rule would match its own pattern text and fail the task.
func GenerateSemgrepIgnore(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder
	b.WriteString("# Semgrep ignore file — auto-generated by qsdev (gitignore syntax).\n")
	b.WriteString("# https://semgrep.dev/docs/ignoring-files-folders-code\n")
	b.WriteString("# The qsdev-security-scan task runs the ecosystem rule packs plus any\n")
	b.WriteString("# project rules in " + ecosystem.SemgrepLocalRulesDir + "/; paths listed here are not scanned.\n")
	for _, p := range defaultScanExcludes {
		b.WriteString(p)
		b.WriteString("\n")
	}
	b.WriteString("# Semgrep rules, not scan targets\n")
	b.WriteString(ecosystem.SemgrepLocalRulesDir + "/\n")

	return &types.GeneratedFile{
		Path:     SemgrepIgnorePath,
		Content:  []byte(b.String()),
		Mode:     fileutil.ModeReadWrite,
		Strategy: types.Overwrite,
		Owner:    "semgrep",
	}, nil
}
