package cigeneration

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// GitHubActionsGenerator produces .github/workflows/security.yml.
type GitHubActionsGenerator struct{}

// jobMeta carries display information for a job.
type jobMeta struct {
	ID        CIJobID
	Name      string
	Condition string // optional if: condition
}

// orderedJobs defines the canonical order and display names for jobs.
var orderedJobs = []jobMeta{
	{ID: JobLintSAST, Name: "Lint & SAST"},
	{ID: JobSecretScan, Name: "Secret Scan"},
	{ID: JobVulnerabilityScan, Name: "Vulnerability Scan"},
	{ID: JobContainerSecurity, Name: "Container Security"},
	{ID: JobSecurityReview, Name: "Security Review", Condition: "github.event_name == 'pull_request'"},
	{ID: JobLicenseCompliance, Name: "License Compliance", Condition: "github.event.schedule != ''"},
}

// Generate builds the GitHub Actions workflow YAML via string builder.
func (g *GitHubActionsGenerator) Generate(cfg GenerateConfig, steps map[CIJobID][]CIStep) ([]types.GeneratedFile, error) {
	var b strings.Builder

	perms := computePermissions(steps)
	hasLicenseCompliance := len(steps[JobLicenseCompliance]) > 0

	// Header
	b.WriteString("# Security scanning workflow\n")
	b.WriteString("# Generated by qsdev — do not edit manually.\n")
	b.WriteString("name: Security\n")

	// Triggers
	b.WriteString("on:\n")
	b.WriteString("  pull_request:\n")
	b.WriteString("  push:\n")
	b.WriteString("    branches: [main, master]\n")
	if hasLicenseCompliance {
		b.WriteString("  schedule:\n")
		b.WriteString("    - cron: '0 6 * * 1'\n")
	}

	// Permissions
	b.WriteString("permissions:\n")
	for _, p := range perms {
		fmt.Fprintf(&b, "  %s: %s\n", p.Scope, p.Level)
	}

	// Jobs
	b.WriteString("jobs:\n")
	for _, jm := range orderedJobs {
		jobSteps, ok := steps[jm.ID]
		if !ok {
			continue
		}
		writeJob(&b, jm, jobSteps)
	}

	content := b.String()
	return []types.GeneratedFile{
		{
			Path:     ".github/workflows/security.yml",
			Content:  []byte(content),
			Mode:     0o644,
			Strategy: types.Overwrite,
			Owner:    "ci-generation",
		},
	}, nil
}

// writeJob emits a single job block.
func writeJob(b *strings.Builder, jm jobMeta, steps []CIStep) {
	fmt.Fprintf(b, "  %s:\n", jm.ID)
	fmt.Fprintf(b, "    name: %s\n", jm.Name)
	if jm.Condition != "" {
		fmt.Fprintf(b, "    if: %s\n", jm.Condition)
	}
	b.WriteString("    runs-on: ubuntu-latest\n")
	b.WriteString("    steps:\n")

	for _, step := range steps {
		writeStep(b, step)
	}
}

// writeStep emits a single step block.
func writeStep(b *strings.Builder, step CIStep) {
	fmt.Fprintf(b, "      - name: %s\n", step.Name)

	if step.Condition != "" {
		fmt.Fprintf(b, "        if: %s\n", step.Condition)
	}

	if step.Uses != "" {
		fmt.Fprintf(b, "        uses: %s %s\n", step.Uses, step.UsesComment)
	}

	if step.Run != "" {
		fmt.Fprintf(b, "        run: %s\n", step.Run)
	}

	if step.ContinueOnError {
		b.WriteString("        continue-on-error: true\n")
	}

	if len(step.With) > 0 {
		b.WriteString("        with:\n")
		keys := sortedKeys(step.With)
		for _, k := range keys {
			fmt.Fprintf(b, "          %s: %s\n", k, step.With[k])
		}
	}

	if len(step.Env) > 0 {
		b.WriteString("        env:\n")
		keys := sortedKeys(step.Env)
		for _, k := range keys {
			fmt.Fprintf(b, "          %s: %s\n", k, step.Env[k])
		}
	}
}

// computePermissions derives workflow-level permissions from the jobs present.
func computePermissions(steps map[CIJobID][]CIStep) []CIPermission {
	perms := []CIPermission{
		{Scope: "contents", Level: "read"},
	}

	// security-events: write needed for SARIF uploads
	for _, jobSteps := range steps {
		for _, s := range jobSteps {
			if strings.Contains(s.Uses, "codeql-action") || strings.HasSuffix(s.Name, "SARIF") {
				perms = append(perms, CIPermission{Scope: "security-events", Level: "write"})
				goto afterSarif
			}
		}
	}
afterSarif:

	// id-token: write needed for cosign
	for _, jobSteps := range steps {
		for _, s := range jobSteps {
			if strings.Contains(s.Uses, "cosign-installer") {
				perms = append(perms, CIPermission{Scope: "id-token", Level: "write"})
				goto afterIDToken
			}
		}
	}
afterIDToken:

	// pull-requests: write needed for Claude Code review
	for _, jobSteps := range steps {
		for _, s := range jobSteps {
			if strings.Contains(s.Uses, "claude-code-action") {
				perms = append(perms, CIPermission{Scope: "pull-requests", Level: "write"})
				goto afterPR
			}
		}
	}
afterPR:

	return perms
}

// sortedKeys returns map keys in sorted order for deterministic output.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
