// Package ruby implements the Ruby (Bundler) ecosystem module for
// qsdev. It detects Ruby projects by scanning for
// Gemfile and Gemfile.lock, generates devenv.nix fragments with Bundler
// support, produces security-hardened Bundler and RubyGems configuration
// files, and provides pre-commit hooks, CI commands, deny rules, and wizard
// fields for the Ruby toolchain.
package ruby

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/internal/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/internal/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// Compile-time interface compliance check.
var _ ecosystem.EcosystemModule = (*Module)(nil)

func init() {
	ecosystem.RegisterModule(&Module{})
}

// Module implements ecosystem.EcosystemModule for the Ruby programming language.
type Module struct{}

// Name returns the canonical ecosystem identifier.
func (m *Module) Name() string { return "ruby" }

// DisplayName returns the human-readable label.
func (m *Module) DisplayName() string { return "Ruby" }

// Tier returns the implementation priority tier.
func (m *Module) Tier() int { return 2 }

// Detect scans projectRoot for Gemfile and Gemfile.lock files and reads
// the Ruby version from a .ruby-version file if present.
func (m *Module) Detect(projectRoot string) ecosystem.DetectionResult {
	gemfile := filepath.Join(projectRoot, "Gemfile")
	gemfileLock := filepath.Join(projectRoot, "Gemfile.lock")

	hasGemfile := fileutil.FileExists(gemfile)
	hasLock := fileutil.FileExists(gemfileLock)

	if !hasGemfile && !hasLock {
		return ecosystem.DetectionResult{
			Detected:   false,
			Confidence: ecosystem.ConfidenceAbsent,
		}
	}

	confidence := ecosystem.ConfidenceProbable
	var evidence []string

	if hasGemfile {
		confidence = ecosystem.ConfidenceCertain
		evidence = append(evidence, "Gemfile found")
	}
	if hasLock {
		if confidence < ecosystem.ConfidenceProbable {
			confidence = ecosystem.ConfidenceProbable
		}
		evidence = append(evidence, "Gemfile.lock found")
	}

	version := parseRubyVersion(projectRoot)
	if version != "" {
		evidence = append(evidence, fmt.Sprintf("Ruby version %s (from .ruby-version)", version))
	}

	return ecosystem.DetectionResult{
		Detected:   true,
		Confidence: confidence,
		Evidence:   evidence,
		SuggestedConfig: ecosystem.ModuleConfig{
			Version: version,
		},
	}
}

// DevenvNixFragment returns the Nix code fragment to include in devenv.nix
// for Ruby language support with Bundler enabled.
func (m *Module) DevenvNixFragment(_ ecosystem.ModuleConfig) (string, error) {
	var b strings.Builder
	b.WriteString("  languages.ruby = {\n")
	b.WriteString("    enable = true;\n")
	b.WriteString("    bundler.enable = true;\n")
	b.WriteString("  };\n")
	return b.String(), nil
}

// DevenvYamlInputs returns additional flake inputs for devenv.yaml.
// Ruby does not require any additional inputs.
func (m *Module) DevenvYamlInputs(_ ecosystem.ModuleConfig) []ecosystem.DevenvInput {
	return nil
}

// SecurityConfigs returns security-hardened Bundler and RubyGems configuration files.
func (m *Module) SecurityConfigs(_ ecosystem.ModuleConfig) []types.GeneratedFile {
	bundleConfig := `# Security-hardened Bundler configuration.
# Generated by qsdev.
# Requires: Bundler >= 2.1 for BUNDLE_FROZEN support.
---
BUNDLE_FROZEN: "true"
BUNDLE_DISABLE_EXEC_LOAD: "true"
`

	gemrc := `# Security-hardened RubyGems configuration.
# Generated by qsdev.
# Enforces HTTPS-only gem sources.
---
:sources:
- https://rubygems.org
gem: --no-document
`

	return []types.GeneratedFile{
		{
			Path:     ".bundle/config",
			Content:  []byte(bundleConfig),
			Mode:     0o644,
			Strategy: types.Overwrite,
		},
		{
			Path:     ".gemrc",
			Content:  []byte(gemrc),
			Mode:     0o644,
			Strategy: types.Overwrite,
		},
	}
}

// PreCommitHooks returns pre-commit hook definitions for the Ruby ecosystem.
func (m *Module) PreCommitHooks(_ ecosystem.ModuleConfig) []ecosystem.HookConfig {
	return []ecosystem.HookConfig{
		{
			ID:            "rubocop",
			Name:          "rubocop",
			Description:   "Run RuboCop linter and formatter for Ruby",
			Entry:         "rubocop --autocorrect",
			Language:      "ruby",
			Types:         []string{"ruby"},
			Stages:        []string{"pre-commit"},
			PassFilenames: true,
			BuiltIn:       true,
		},
	}
}

// DenyRules returns Claude Code deny-rule patterns for the Ruby ecosystem.
// These prevent direct dependency modification outside of controlled workflows.
func (m *Module) DenyRules(_ ecosystem.ModuleConfig) []string {
	// Package install commands (gem/bundle) are handled by base ask rules +
	// package-guard hook. Return empty — no Ruby-specific hard-deny patterns.
	return nil
}

// CICommands returns CI pipeline commands for the Ruby ecosystem.
func (m *Module) CICommands(_ ecosystem.ModuleConfig) []ecosystem.CICommand {
	return []ecosystem.CICommand{
		{
			Name:        "bundle-install",
			Command:     "bundle install --frozen",
			Description: "Install Ruby dependencies from frozen Gemfile.lock",
			Phase:       ecosystem.CIPhaseInstall,
		},
		{
			Name:        "bundle-audit",
			Command:     "bundle audit check --update",
			Description: "Audit Ruby dependencies for known vulnerabilities",
			Phase:       ecosystem.CIPhaseScan,
		},
	}
}

// PackageManagers returns metadata about Ruby's Bundler package manager.
func (m *Module) PackageManagers() []ecosystem.PackageManagerInfo {
	return []ecosystem.PackageManagerInfo{
		{
			Name:                 "bundler",
			LockFile:             "Gemfile.lock",
			InstallCommand:       "bundle install",
			FrozenInstallCommand: "bundle install --frozen",
			AuditCommand:         "bundle audit check",
			AgeGatingSupport:     false,
		},
	}
}

// WizardFields returns additional wizard form fields for Ruby configuration.
func (m *Module) WizardFields() []ecosystem.WizardField {
	return []ecosystem.WizardField{
		{
			Key:         "ruby_version",
			Label:       "Ruby version",
			Description: "Specify the Ruby version to use (e.g. 3.3)",
			Type:        ecosystem.FieldTypeInput,
			Default:     "",
		},
	}
}

// VerificationCommands returns test and lint commands for Ruby projects.
func (m *Module) VerificationCommands(_ ecosystem.ModuleConfig) ecosystem.VerificationCommands {
	return ecosystem.VerificationCommands{
		Test: []string{"bundle exec rspec"},
		Lint: []string{"bundle exec rubocop"},
	}
}

// ManifestFiles returns the Gemfile manifest file for Ruby projects.
func (m *Module) ManifestFiles(_ ecosystem.ModuleConfig) []ecosystem.ManifestFileInfo {
	return []ecosystem.ManifestFileInfo{{Path: "Gemfile", Ecosystem: "bundler", LockFile: "Gemfile.lock", LockFilePolicy: ecosystem.LockFilePolicyRequired}}
}

// parseRubyVersion reads .ruby-version in projectRoot and returns the
// trimmed first line. Returns an empty string if the file does not exist
// or cannot be read.
func parseRubyVersion(projectRoot string) string {
	data, err := os.ReadFile(filepath.Join(projectRoot, ".ruby-version"))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(data))
}
