// Package javascript implements the JavaScript/TypeScript ecosystem module
// for qsdev. It detects Node.js projects, determines
// the package manager in use, and generates security-hardened configurations.
package javascript

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// yarnClassicLockHeader is the marker line Yarn Classic (v1) writes at the
// top of yarn.lock. Yarn Berry (v2+) writes a YAML lockfile with a
// "__metadata:" entry instead.
const yarnClassicLockHeader = "# yarn lockfile v1"

// isYarnClassic reports whether the Yarn project at projectRoot uses Yarn
// Classic (v1). An explicit package.json "packageManager" pin wins; otherwise
// the yarn.lock header decides.
func isYarnClassic(projectRoot string) bool {
	if pin := packageManagerPin(filepath.Join(projectRoot, "package.json")); strings.HasPrefix(pin, "yarn@") {
		return strings.HasPrefix(pin, "yarn@1.")
	}

	f, err := os.Open(filepath.Join(projectRoot, "yarn.lock"))
	if err != nil {
		return false
	}
	defer f.Close() //nolint:errcheck // read-only

	// The header sits within the first few lines (after the "THIS IS AN
	// AUTOGENERATED FILE" banner).
	scanner := bufio.NewScanner(f)
	for i := 0; i < 5 && scanner.Scan(); i++ {
		if strings.TrimSpace(scanner.Text()) == yarnClassicLockHeader {
			return true
		}
	}
	return false
}

// packageManagerPin returns package.json's "packageManager" field
// (e.g. "yarn@1.22.22"), or "" when absent or unparseable.
func packageManagerPin(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	var pkg struct {
		PackageManager string `json:"packageManager"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return ""
	}
	return strings.TrimSpace(pkg.PackageManager)
}

// nodeVersionFromPackageJSON extracts the Node.js version constraint from
// the "engines.node" field in package.json at the given directory path.
// Returns an empty string if the field is absent or unparseable.
func nodeVersionFromPackageJSON(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}

	var pkg struct {
		Engines struct {
			Node string `json:"node"`
		} `json:"engines"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return ""
	}
	return pkg.Engines.Node
}

// extractMajorVersion strips common version prefixes (v, >=, ^, ~, =)
// and returns the first numeric segment as an integer.
// Returns 0 if parsing fails.
func extractMajorVersion(version string) int {
	if version == "" {
		return 0
	}

	// Strip common prefixes.
	v := version
	for _, prefix := range []string{">=", "<=", "^", "~", "=", "v", ">", "<"} {
		v = strings.TrimPrefix(v, prefix)
	}
	v = strings.TrimSpace(v)

	// Take the first numeric segment (before '.', '-', or ' ').
	for i, ch := range v {
		if ch == '.' || ch == '-' || ch == ' ' {
			v = v[:i]
			break
		}
	}

	n, err := strconv.Atoi(v)
	if err != nil {
		return 0
	}
	return n
}

// nodeNixPackage maps a major Node.js version to the corresponding
// nixpkgs attribute. Defaults to pkgs.nodejs_22 for unknown versions.
func nodeNixPackage(majorVersion int) string {
	switch majorVersion {
	case 18:
		return "pkgs.nodejs_18"
	case 20:
		return "pkgs.nodejs_20"
	case 22:
		return "pkgs.nodejs_22"
	case 24:
		return "pkgs.nodejs_24"
	default:
		return "pkgs.nodejs_22"
	}
}
