// Package javascript implements the JavaScript/TypeScript ecosystem module
// for qsdev. It detects Node.js projects, determines
// the package manager in use, and generates security-hardened configurations.
package javascript

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
)

// yarnClassicLockHeader is the marker line Yarn Classic (v1) writes at the
// top of yarn.lock. Yarn Berry (v2+) writes a YAML lockfile with a
// "__metadata:" entry instead.
const yarnClassicLockHeader = "# yarn lockfile v1"

// packageJSON holds the package.json fields the module inspects.
type packageJSON struct {
	PackageManager string `json:"packageManager"`
	DevEngines     struct {
		// PackageManager is an object or an array of objects
		// ({"name": "pnpm", "version": "^10"}).
		PackageManager json.RawMessage `json:"packageManager"`
	} `json:"devEngines"`
	Engines struct {
		Node string `json:"node"`
	} `json:"engines"`
	Dependencies    map[string]string `json:"dependencies"`
	DevDependencies map[string]string `json:"devDependencies"`
	ESLintConfig    json.RawMessage   `json:"eslintConfig"`
	Prettier        json.RawMessage   `json:"prettier"`
}

// readPackageJSON parses the package.json at path. ok is false when the file
// is missing or not valid JSON.
func readPackageJSON(path string) (pkg packageJSON, ok bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return packageJSON{}, false
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return packageJSON{}, false
	}
	return pkg, true
}

// hasDependency reports whether name is a runtime or dev dependency.
func (p packageJSON) hasDependency(name string) bool {
	_, dep := p.Dependencies[name]
	_, dev := p.DevDependencies[name]
	return dep || dev
}

// packageManagerPin returns the package manager the project pins, as a name
// ("pnpm") and version ("10.17.0", possibly a range for devEngines). The
// Corepack "packageManager" field wins over devEngines.packageManager; both
// are empty when neither is set.
func (p packageJSON) packageManagerPin() (name, version string) {
	if pin := strings.TrimSpace(p.PackageManager); pin != "" {
		name, version, _ = strings.Cut(pin, "@")
		// Corepack allows a "+sha512.<hash>" integrity suffix.
		version, _, _ = strings.Cut(version, "+")
		return name, version
	}

	type engine struct {
		Name    string `json:"name"`
		Version string `json:"version"`
	}
	var one engine
	if err := json.Unmarshal(p.DevEngines.PackageManager, &one); err == nil && one.Name != "" {
		return one.Name, one.Version
	}
	var many []engine
	if err := json.Unmarshal(p.DevEngines.PackageManager, &many); err == nil && len(many) > 0 {
		return many[0].Name, many[0].Version
	}
	return "", ""
}

// isYarnClassic reports whether the Yarn project at projectRoot uses Yarn
// Classic (v1). An explicit package.json package-manager pin wins; otherwise
// the yarn.lock header decides.
func isYarnClassic(projectRoot string, pkg packageJSON) bool {
	if name, version := pkg.packageManagerPin(); name == "yarn" {
		if major, _, _, ok := parseVersion(version); ok {
			return major == 1
		}
	}

	f, err := os.Open(filepath.Join(projectRoot, "yarn.lock"))
	if err != nil {
		return false
	}
	defer f.Close() //nolint:errcheck // read-only

	// The header sits within the first few lines (after the "THIS IS AN
	// AUTOGENERATED FILE" banner).
	scanner := bufio.NewScanner(f)
	for i := 0; i < 5 && scanner.Scan(); i++ {
		if strings.TrimSpace(scanner.Text()) == yarnClassicLockHeader {
			return true
		}
	}
	return false
}

// eslintConfigFiles and prettierConfigFiles are the project-root config files
// each tool loads on its own.
var (
	eslintConfigFiles = []string{
		"eslint.config.js", "eslint.config.mjs", "eslint.config.cjs",
		"eslint.config.ts", "eslint.config.mts", "eslint.config.cts",
		".eslintrc", ".eslintrc.js", ".eslintrc.cjs", ".eslintrc.yaml",
		".eslintrc.yml", ".eslintrc.json",
	}
	prettierConfigFiles = []string{
		".prettierrc", ".prettierrc.json", ".prettierrc.yaml", ".prettierrc.yml",
		".prettierrc.json5", ".prettierrc.js", ".prettierrc.cjs", ".prettierrc.mjs",
		".prettierrc.ts", ".prettierrc.mts", ".prettierrc.cts", ".prettierrc.toml",
		"prettier.config.js", "prettier.config.cjs", "prettier.config.mjs",
		"prettier.config.ts", "prettier.config.mts", "prettier.config.cts",
	}
)

// Values of the ExtraESLint / ExtraPrettier extras: where the tool comes from.
const (
	// toolFromNodeModules means the project depends on the tool, so the hook
	// runs the project's own copy (and plugins) from node_modules/.bin.
	toolFromNodeModules = "node_modules"
	// toolFromNix means the project configures the tool without depending on
	// it, so the hook runs the nixpkgs build.
	toolFromNix = "nix"
)

// detectJSTool reports whether the project uses a JS tool (eslint, prettier)
// and where its hook should run it from. It returns "" when the project has
// neither a config file nor a dependency on the tool, so the hook is not
// forced onto projects that never adopted it.
func detectJSTool(projectRoot string, pkg packageJSON, dependency string, configFiles []string, inlineConfig json.RawMessage) string {
	if pkg.hasDependency(dependency) {
		return toolFromNodeModules
	}
	if len(inlineConfig) > 0 {
		return toolFromNix
	}
	for _, name := range configFiles {
		if fileutil.FileExists(filepath.Join(projectRoot, name)) {
			return toolFromNix
		}
	}
	return ""
}
