package javascript_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/BurntSushi/toml"

	"github.com/Quantum-Serendipity/qsdev/pkg/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/pkg/ecosystem/modules/javascript"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// TestSecurityConfigs_NeverOverwriteUserFiles guards against replacing a
// pre-existing, user-maintained package manager config (pnpm workspace list,
// .npmrc scoped registries, .yarnrc.yml plugins) on first generation.
func TestSecurityConfigs_NeverOverwriteUserFiles(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		cfg  ecosystem.ModuleConfig
	}{
		{"npm", ecosystem.ModuleConfig{PackageManager: "npm"}},
		{"pnpm", ecosystem.ModuleConfig{PackageManager: "pnpm"}},
		{"yarn berry", ecosystem.ModuleConfig{PackageManager: "yarn"}},
		{"yarn classic", ecosystem.ModuleConfig{PackageManager: "yarn", Extras: map[string]string{javascript.ExtraYarnClassic: "true"}}},
		{"bun", ecosystem.ModuleConfig{PackageManager: "bun"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			for _, f := range (&javascript.Module{}).SecurityConfigs(tt.cfg) {
				if f.Strategy != types.Skip {
					t.Errorf("%s Strategy = %v, want Skip", f.Path, f.Strategy)
				}
			}
		})
	}
}

// TestSecurityConfigs_BunMinimumReleaseAgeIsIntegerSeconds verifies the Bun
// age gate is a TOML integer (seconds). A string such as "7d" makes
// `bun install` fail with "Expected number of seconds for minimumReleaseAge".
func TestSecurityConfigs_BunMinimumReleaseAgeIsIntegerSeconds(t *testing.T) {
	t.Parallel()
	configs := (&javascript.Module{}).SecurityConfigs(ecosystem.ModuleConfig{PackageManager: "bun"})
	if len(configs) != 1 {
		t.Fatalf("got %d configs, want 1", len(configs))
	}

	var parsed struct {
		Install map[string]any `toml:"install"`
	}
	if _, err := toml.Decode(string(configs[0].Content), &parsed); err != nil {
		t.Fatalf("bunfig.toml is not valid TOML: %v\n%s", err, configs[0].Content)
	}
	got, ok := parsed.Install["minimumReleaseAge"].(int64)
	if !ok {
		t.Fatalf("install.minimumReleaseAge = %#v (%T), want an integer number of seconds",
			parsed.Install["minimumReleaseAge"], parsed.Install["minimumReleaseAge"])
	}
	if want := int64(7 * 24 * 60 * 60); got != want {
		t.Errorf("install.minimumReleaseAge = %d, want %d (7 days)", got, want)
	}
}

func TestSecurityConfigs_YarnClassic(t *testing.T) {
	t.Parallel()
	configs := (&javascript.Module{}).SecurityConfigs(ecosystem.ModuleConfig{
		PackageManager: "yarn",
		Extras:         map[string]string{javascript.ExtraYarnClassic: "true"},
		RegistryProxy:  "https://proxy.example.com/npm/",
	})
	if len(configs) != 1 {
		t.Fatalf("got %d configs, want 1", len(configs))
	}
	cfg := configs[0]
	if cfg.Path != ".yarnrc" {
		t.Errorf("Path = %q, want .yarnrc (Yarn Classic never reads .yarnrc.yml)", cfg.Path)
	}
	content := string(cfg.Content)
	for _, want := range []string{
		"ignore-scripts true\n",
		`registry "https://proxy.example.com/npm/"` + "\n",
	} {
		if !strings.Contains(content, want) {
			t.Errorf(".yarnrc missing %q\ncontent:\n%s", want, content)
		}
	}
	for _, berryOnly := range []string{"enableScripts", "enableHardenedMode", "npmMinimalAgeGate"} {
		if strings.Contains(content, berryOnly) {
			t.Errorf(".yarnrc contains Berry-only key %q\ncontent:\n%s", berryOnly, content)
		}
	}
}

// TestCICommands_YarnFrozenInstallFlag verifies the CI install uses the
// frozen-lockfile flag each Yarn generation understands.
func TestCICommands_YarnFrozenInstallFlag(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		extras map[string]string
		want   string
	}{
		{"berry", nil, "yarn install --immutable"},
		{"classic", map[string]string{javascript.ExtraYarnClassic: "true"}, "yarn install --frozen-lockfile --ignore-scripts"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			cmds := (&javascript.Module{}).CICommands(ecosystem.ModuleConfig{PackageManager: "yarn", Extras: tt.extras})
			if len(cmds) == 0 || cmds[0].Command != tt.want {
				t.Errorf("install command = %v, want %q", cmds, tt.want)
			}
		})
	}
}

func TestDetect_YarnFlavor(t *testing.T) {
	t.Parallel()
	const classicLock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\nleft-pad@^1.3.0:\n  version \"1.3.0\"\n"
	const berryLock = "# This file is generated by running \"yarn install\" inside your project.\n\n__metadata:\n  version: 8\n"
	tests := []struct {
		name        string
		packageJSON string
		yarnLock    string
		wantClassic bool
	}{
		{"v1 lockfile header", `{}`, classicLock, true},
		{"berry lockfile", `{}`, berryLock, false},
		{"packageManager pins yarn 1", `{"packageManager":"yarn@1.22.22"}`, berryLock, true},
		{"packageManager pins yarn 4", `{"packageManager":"yarn@4.5.0"}`, classicLock, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			writeTestFile(t, dir, "package.json", tt.packageJSON)
			writeTestFile(t, dir, "yarn.lock", tt.yarnLock)

			res := (&javascript.Module{}).Detect(dir)
			if res.SuggestedConfig.PackageManager != "yarn" {
				t.Fatalf("PackageManager = %q, want yarn", res.SuggestedConfig.PackageManager)
			}
			got := res.SuggestedConfig.Extras[javascript.ExtraYarnClassic] == "true"
			if got != tt.wantClassic {
				t.Errorf("yarn classic = %v, want %v", got, tt.wantClassic)
			}
		})
	}
}

func writeTestFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
