// Package java provides XML struct types and rendering helpers for generating
// a security-hardened Maven settings.xml.
package java

import (
	"bytes"
	"encoding/xml"
)

// Settings is the root element of a Maven settings.xml file.
type Settings struct {
	XMLName        xml.Name       `xml:"settings"`
	Xmlns          string         `xml:"xmlns,attr"`
	Profiles       Profiles       `xml:"profiles"`
	ActiveProfiles ActiveProfiles `xml:"activeProfiles"`
	Mirrors        Mirrors        `xml:"mirrors"`
}

// Profiles wraps a list of Maven profiles.
type Profiles struct {
	Profile []Profile `xml:"profile"`
}

// Profile is a single Maven build profile.
type Profile struct {
	ID           string       `xml:"id"`
	Repositories Repositories `xml:"repositories"`
}

// Repositories wraps a list of Maven repositories.
type Repositories struct {
	Repository []Repository `xml:"repository"`
}

// Repository defines a single Maven artifact repository.
type Repository struct {
	ID        string `xml:"id"`
	URL       string `xml:"url"`
	Releases  Policy `xml:"releases"`
	Snapshots Policy `xml:"snapshots"`
}

// Policy defines the Maven update/checksum policy for a repository channel.
type Policy struct {
	Enabled        string `xml:"enabled"`
	ChecksumPolicy string `xml:"checksumPolicy,omitempty"`
}

// ActiveProfiles wraps the list of active profile IDs.
type ActiveProfiles struct {
	ActiveProfile []string `xml:"activeProfile"`
}

// Mirrors wraps a list of Maven mirror definitions.
type Mirrors struct {
	Mirror []Mirror `xml:"mirror"`
}

// Mirror defines a Maven repository mirror.
type Mirror struct {
	ID       string `xml:"id"`
	Name     string `xml:"name"`
	URL      string `xml:"url"`
	MirrorOf string `xml:"mirrorOf"`
}

// buildSecuritySettings returns a Settings struct configured for supply-chain
// security: strict checksum enforcement, snapshot blocking, and a mirror that
// forces all traffic through Maven Central.
func buildSecuritySettings() Settings {
	return Settings{
		Xmlns: "http://maven.apache.org/SETTINGS/1.2.0",
		Profiles: Profiles{
			Profile: []Profile{
				{
					ID: "security-hardened",
					Repositories: Repositories{
						Repository: []Repository{
							{
								ID:  "central",
								URL: "https://repo.maven.apache.org/maven2",
								Releases: Policy{
									Enabled:        "true",
									ChecksumPolicy: "fail",
								},
								Snapshots: Policy{
									Enabled: "false",
								},
							},
						},
					},
				},
			},
		},
		ActiveProfiles: ActiveProfiles{
			ActiveProfile: []string{"security-hardened"},
		},
		Mirrors: Mirrors{
			Mirror: []Mirror{
				{
					ID:       "central-only",
					Name:     "Block non-central repositories",
					URL:      "https://repo.maven.apache.org/maven2",
					MirrorOf: "*",
				},
			},
		},
	}
}

// xmlHeader is prepended to the rendered XML output.
const xmlHeader = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by gdev-secure-devenv-bootstrap — supply-chain security hardened.
     Requires: Maven >= 3.2.5 for checksumPolicy, Maven >= 3.8.1 for HTTP blocking.
     checksumPolicy=fail, snapshots disabled, non-central repos blocked via mirror. -->
`

// renderSettingsXML marshals a Settings struct to indented XML with
// the standard XML declaration and a descriptive comment header.
func renderSettingsXML(s Settings) ([]byte, error) {
	body, err := xml.MarshalIndent(s, "", "  ")
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString(xmlHeader)
	buf.Write(body)
	buf.WriteByte('\n')
	return buf.Bytes(), nil
}
