// Package docker implements the Docker / Containerfiles ecosystem module for
// qsdev. It detects Dockerfiles, Containerfiles, and
// docker-compose manifests, generates devenv.nix fragments with container
// tooling, and provides hadolint linting, image scanning, and signing CI
// commands alongside Claude Code deny rules.
package docker

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Quantum-Serendipity/qsdev/internal/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/internal/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// Compile-time interface compliance checks.
var _ ecosystem.EcosystemModule = (*Module)(nil)
var _ ecosystem.SecretDeclarer = (*Module)(nil)

func init() {
	ecosystem.RegisterModule(&Module{})
}

// Module implements ecosystem.EcosystemModule for Docker / Containerfiles.
type Module struct{}

// Name returns the canonical ecosystem identifier.
func (m *Module) Name() string { return "docker" }

// DisplayName returns the human-readable label.
func (m *Module) DisplayName() string { return "Docker / Containerfiles" }

// Tier returns the implementation priority tier.
func (m *Module) Tier() int { return 1 }

// Detect scans projectRoot for Docker-related files and returns a
// DetectionResult with accumulated evidence.
func (m *Module) Detect(projectRoot string) ecosystem.DetectionResult {
	var (
		evidence   []string
		confidence = ecosystem.ConfidenceAbsent
		detected   bool
		hasCompose bool
	)

	// Certain indicators.
	if fileutil.FileExists(projectRoot, "Dockerfile") {
		evidence = append(evidence, "Dockerfile found")
		confidence = ecosystem.ConfidenceCertain
		detected = true
	}
	if fileutil.FileExists(projectRoot, "Containerfile") {
		evidence = append(evidence, "Containerfile found")
		confidence = ecosystem.ConfidenceCertain
		detected = true
	}

	// Probable indicators.
	for _, name := range []string{"docker-compose.yml", "docker-compose.yaml"} {
		if fileutil.FileExists(projectRoot, name) {
			evidence = append(evidence, name+" found")
			hasCompose = true
			if confidence < ecosystem.ConfidenceProbable {
				confidence = ecosystem.ConfidenceProbable
			}
			detected = true
		}
	}
	if fileutil.FileExists(projectRoot, ".dockerignore") {
		evidence = append(evidence, ".dockerignore found")
		if confidence < ecosystem.ConfidenceProbable {
			confidence = ecosystem.ConfidenceProbable
		}
		detected = true
	}

	if !detected {
		return ecosystem.DetectionResult{
			Detected:   false,
			Confidence: ecosystem.ConfidenceAbsent,
		}
	}

	config := ecosystem.ModuleConfig{
		Extras: make(map[string]string),
	}
	if hasCompose {
		config.Extras["has_compose"] = "true"
	}

	return ecosystem.DetectionResult{
		Detected:        true,
		Confidence:      confidence,
		Evidence:        evidence,
		SuggestedConfig: config,
	}
}

// DevenvNixFragment returns the Nix code fragment to include in devenv.nix
// for Docker tooling. Docker has no devenv.sh language module, so only
// packages are added.
func (m *Module) DevenvNixFragment(_ ecosystem.ModuleConfig) (string, error) {
	var b strings.Builder
	b.WriteString("  packages = with pkgs; [\n")
	b.WriteString("    docker\n")
	b.WriteString("    hadolint\n")
	b.WriteString("    dive\n")
	b.WriteString("  ];\n")
	return b.String(), nil
}

// DevenvYamlInputs returns additional flake inputs for devenv.yaml.
// Docker does not require any additional inputs.
func (m *Module) DevenvYamlInputs(_ ecosystem.ModuleConfig) []ecosystem.DevenvInput {
	return nil
}

// hadolintConfig is the structured representation of .hadolint.yaml.
type hadolintConfig struct {
	TrustedRegistries []string `yaml:"trustedRegistries"`
	FailureThreshold  string   `yaml:"failure-threshold"`
}

// defaultTrustedRegistries lists registries trusted by default.
var defaultTrustedRegistries = []string{
	"docker.io",
	"gcr.io",
	"ghcr.io",
}

// hadolintHeader is prepended to the generated .hadolint.yaml file.
const hadolintHeader = `# Hadolint configuration — generated by qsdev.
# Requires: hadolint (any version). Available via nixpkgs.
# trustedRegistries: only images from these registries pass the
#   DL3026 (use only trusted base images) rule.
# failure-threshold: lint warnings at or above this severity fail the check.
`

// SecurityConfigs returns the generated .hadolint.yaml configuration file.
func (m *Module) SecurityConfigs(config ecosystem.ModuleConfig) []types.GeneratedFile {
	registries := defaultTrustedRegistries

	if custom, ok := config.Extras["trusted_registries"]; ok && custom != "" {
		parts := strings.Split(custom, ",")
		parsed := make([]string, 0, len(parts))
		for _, p := range parts {
			trimmed := strings.TrimSpace(p)
			if trimmed != "" {
				parsed = append(parsed, trimmed)
			}
		}
		if len(parsed) > 0 {
			registries = parsed
		}
	}

	cfg := hadolintConfig{
		TrustedRegistries: registries,
		FailureThreshold:  "warning",
	}

	var buf bytes.Buffer
	buf.WriteString(hadolintHeader)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&cfg); err != nil {
		// Should never happen with simple struct; degrade gracefully.
		fmt.Fprintf(&buf, "# error encoding hadolint config: %v\n", err)
	}
	_ = enc.Close() //nolint:errcheck

	return []types.GeneratedFile{
		{
			Path:     ".hadolint.yaml",
			Content:  buf.Bytes(),
			Mode:     0644,
			Strategy: types.Overwrite,
		},
	}
}

// PreCommitHooks returns pre-commit hook definitions for the Docker ecosystem.
func (m *Module) PreCommitHooks(_ ecosystem.ModuleConfig) []ecosystem.HookConfig {
	return []ecosystem.HookConfig{
		{
			ID:            "hadolint",
			Name:          "hadolint",
			Description:   "Lint Dockerfiles with hadolint",
			Entry:         "hadolint",
			Language:      "system",
			Types:         []string{"dockerfile"},
			Stages:        []string{"pre-commit"},
			PassFilenames: true,
			Files:         `(Dockerfile|Containerfile)`,
			BuiltIn:       false,
		},
	}
}

// DenyRules returns Claude Code deny-rule patterns for the Docker ecosystem.
// Prevents uncontrolled image pulls that could introduce untrusted images.
func (m *Module) DenyRules(_ ecosystem.ModuleConfig) []string {
	return []string{
		"Bash(docker pull *)",
	}
}

// CICommands returns CI pipeline commands for the Docker ecosystem.
func (m *Module) CICommands(_ ecosystem.ModuleConfig) []ecosystem.CICommand {
	return []ecosystem.CICommand{
		{
			Name:        "hadolint",
			Command:     "hadolint Dockerfile",
			Description: "Lint Dockerfile for best-practice violations",
			Phase:       ecosystem.CIPhaseScan,
		},
		{
			Name:        "docker-build",
			Command:     "docker build --no-cache .",
			Description: "Build container image without layer cache to verify reproducibility",
			Phase:       ecosystem.CIPhaseScan,
		},
		{
			Name:        "trivy-image",
			Command:     "trivy image --severity HIGH,CRITICAL --exit-code 1 $(docker images -q | head -1)",
			Description: "Scan container image for OS and library vulnerabilities with Trivy (note: Trivy's maintainer Aqua Security suffered a supply-chain compromise in March 2026 — pin to a verified hash and monitor advisories)",
			Phase:       ecosystem.CIPhaseScan,
		},
		{
			Name:        "cosign-verify",
			Command:     "cosign verify --key cosign.pub $(docker images --format '{{.Repository}}:{{.Tag}}' | head -1)",
			Description: "Verify container image signature with cosign",
			Phase:       ecosystem.CIPhaseScan,
		},
	}
}

// PackageManagers returns metadata about Docker's package management.
// Docker is not a package manager, so this returns nil.
func (m *Module) PackageManagers() []ecosystem.PackageManagerInfo {
	return nil
}

// WizardFields returns additional wizard form fields for Docker configuration.
func (m *Module) WizardFields() []ecosystem.WizardField {
	return []ecosystem.WizardField{
		{
			Key:         "trusted_registries",
			Label:       "Trusted container registries",
			Description: "Comma-separated list of container registries to trust in hadolint",
			Type:        ecosystem.FieldTypeInput,
			Default:     "docker.io,gcr.io,ghcr.io",
		},
	}
}

// VerificationCommands returns project verification commands for the Docker ecosystem.
func (m *Module) VerificationCommands(_ ecosystem.ModuleConfig) ecosystem.VerificationCommands {
	return ecosystem.VerificationCommands{
		Build: []string{"docker build ."},
		Lint:  []string{"hadolint Dockerfile"},
	}
}

// ManifestFiles returns manifest file metadata for the Docker ecosystem.
func (m *Module) ManifestFiles(_ ecosystem.ModuleConfig) []ecosystem.ManifestFileInfo {
	return nil
}

// SecretDeclarations returns the secrets required by a Docker project.
func (m *Module) SecretDeclarations(_ ecosystem.ModuleConfig) []ecosystem.SecretDecl {
	return []ecosystem.SecretDecl{
		{
			Name:        "DOCKER_REGISTRY_TOKEN",
			Description: "Authentication token for private Docker registry",
			Required:    true,
			Source:      "docker",
		},
	}
}

// SemgrepRuleSets returns Semgrep rule set identifiers relevant to Docker projects.
func (m *Module) SemgrepRuleSets() []string {
	return []string{"p/dockerfile"}
}

