package javascript

import (
	"fmt"
	"os"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/internal/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
	"gopkg.in/yaml.v3"
)

// SecurityConfigs returns generated security configuration files for the
// detected (or user-selected) package manager. Only one PM-specific config
// is generated per invocation.
func (m *Module) SecurityConfigs(config ecosystem.ModuleConfig) []types.GeneratedFile {
	pm := config.PackageManager
	if pm == "" {
		pm = "npm"
	}

	switch pm {
	case "npm":
		return []types.GeneratedFile{npmSecurityConfig(config.RegistryProxy)}
	case "pnpm":
		return []types.GeneratedFile{pnpmSecurityConfig(config.RegistryProxy)}
	case "yarn":
		return []types.GeneratedFile{yarnSecurityConfig(config.RegistryProxy)}
	case "bun":
		return []types.GeneratedFile{bunSecurityConfig()}
	default:
		return []types.GeneratedFile{npmSecurityConfig(config.RegistryProxy)}
	}
}

// npmSecurityConfig generates a hardened .npmrc in INI format.
func npmSecurityConfig(registryProxy string) types.GeneratedFile {
	var b strings.Builder
	b.WriteString("# Security-hardened npm configuration\n")
	b.WriteString("# Generated by qsdev - do not remove security settings\n")
	b.WriteString("# Requires: npm >= 11.10.0 for min-release-age support (Feb 2026)\n")
	b.WriteString("\n")
	if registryProxy != "" {
		fmt.Fprintf(&b, "registry=%s\n", registryProxy)
	}
	b.WriteString("# Pin exact versions to prevent unexpected updates\n")
	b.WriteString("save-exact=true\n")
	b.WriteString("# Disable lifecycle scripts to block malicious postinstall hooks\n")
	b.WriteString("ignore-scripts=true\n")
	b.WriteString("# Require packages to be published for at least 3 days\n")
	b.WriteString("min-release-age=3\n")
	b.WriteString("# Enable automatic security auditing on install\n")
	b.WriteString("audit=true\n")
	b.WriteString("# Fail on moderate and above vulnerabilities\n")
	b.WriteString("audit-level=moderate\n")

	return types.GeneratedFile{
		Path:     ".npmrc",
		Content:  []byte(b.String()),
		Mode:     os.FileMode(0o644),
		Strategy: types.Overwrite,
	}
}

// pnpmSecurityConfig generates a hardened pnpm-workspace.yaml using yaml.Node
// for comment support. Note: pnpm uses MINUTES for minimumReleaseAge (4320 = 3 days).
func pnpmSecurityConfig(registryProxy string) types.GeneratedFile {
	mappingContent := []*yaml.Node{}

	if registryProxy != "" {
		mappingContent = append(mappingContent,
			&yaml.Node{
				Kind:        yaml.ScalarNode,
				Value:       "npmRegistryServer",
				LineComment: "Corporate registry proxy",
			},
			&yaml.Node{Kind: yaml.ScalarNode, Value: registryProxy},
		)
	}

	mappingContent = append(mappingContent,
		&yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       "strictDepBuilds",
			LineComment: "Prevent dependency build scripts from running without approval",
		},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "true", Tag: "!!bool"},
		&yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       "minimumReleaseAge",
			LineComment: "Require packages to be published for at least 3 days (4320 minutes)",
		},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "4320", Tag: "!!int"},
		&yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       "trustPolicy",
			LineComment: "Prevent trust-level downgrades in dependencies",
		},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "no-downgrade"},
		&yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       "blockExoticSubdeps",
			LineComment: "Block exotic protocols (git:, http:) in transitive dependencies",
		},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "true", Tag: "!!bool"},
	)

	doc := &yaml.Node{
		Kind: yaml.DocumentNode,
		Content: []*yaml.Node{
			{
				Kind:        yaml.MappingNode,
				HeadComment: "Security-hardened pnpm workspace configuration\nGenerated by qsdev - do not remove security settings\nRequires: pnpm >= 10.16 (Sep 2025); these settings are defaults in pnpm 11",
				Content:     mappingContent,
			},
		},
	}

	content, err := yaml.Marshal(doc)
	if err != nil {
		// Fallback to string-built content if marshaling fails.
		content = []byte("# Security-hardened pnpm workspace configuration\nstrictDepBuilds: true\nminimumReleaseAge: 4320\ntrustPolicy: no-downgrade\nblockExoticSubdeps: true\n")
	}

	return types.GeneratedFile{
		Path:     "pnpm-workspace.yaml",
		Content:  content,
		Mode:     os.FileMode(0o644),
		Strategy: types.Overwrite,
	}
}

// yarnSecurityConfig generates a hardened .yarnrc.yml using yaml.Node
// for comment support.
func yarnSecurityConfig(registryProxy string) types.GeneratedFile {
	mappingContent := []*yaml.Node{}

	if registryProxy != "" {
		mappingContent = append(mappingContent,
			&yaml.Node{
				Kind:        yaml.ScalarNode,
				Value:       "npmRegistryServer",
				LineComment: "Corporate registry proxy",
			},
			&yaml.Node{Kind: yaml.ScalarNode, Value: registryProxy},
		)
	}

	mappingContent = append(mappingContent,
		&yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       "enableImmutableInstalls",
			LineComment: "Prevent lockfile modifications during install",
		},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "true", Tag: "!!bool"},
		&yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       "enableHardenedMode",
			LineComment: "Enable Yarn's hardened security mode",
		},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "true", Tag: "!!bool"},
		&yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       "enableScripts",
			LineComment: "Disable lifecycle scripts to block malicious hooks",
		},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "false", Tag: "!!bool"},
		&yaml.Node{
			Kind:        yaml.ScalarNode,
			Value:       "npmMinimalAgeGate",
			LineComment: "Require packages to be published for at least 7 days",
		},
		&yaml.Node{Kind: yaml.ScalarNode, Value: "7d"},
	)

	doc := &yaml.Node{
		Kind: yaml.DocumentNode,
		Content: []*yaml.Node{
			{
				Kind:        yaml.MappingNode,
				HeadComment: "Security-hardened Yarn configuration\nGenerated by qsdev - do not remove security settings\nRequires: Yarn >= 4.10.0 (Sep 2025)",
				Content:     mappingContent,
			},
		},
	}

	content, err := yaml.Marshal(doc)
	if err != nil {
		content = []byte("# Security-hardened Yarn configuration\nenableImmutableInstalls: true\nenableHardenedMode: true\nenableScripts: false\nnpmMinimalAgeGate: 7d\n")
	}

	return types.GeneratedFile{
		Path:     ".yarnrc.yml",
		Content:  content,
		Mode:     os.FileMode(0o644),
		Strategy: types.Overwrite,
	}
}

// bunSecurityConfig generates a hardened bunfig.toml in string-built TOML format.
func bunSecurityConfig() types.GeneratedFile {
	var b strings.Builder
	b.WriteString("# Security-hardened Bun configuration\n")
	b.WriteString("# Generated by qsdev - do not remove security settings\n")
	b.WriteString("# Requires: Bun >= 1.3 (Oct 2025)\n")
	b.WriteString("\n")
	b.WriteString("[install]\n")
	b.WriteString("# Require packages to be published for at least 7 days\n")
	b.WriteString("minimumReleaseAge = \"7d\"\n")

	return types.GeneratedFile{
		Path:     "bunfig.toml",
		Content:  []byte(b.String()),
		Mode:     os.FileMode(0o644),
		Strategy: types.Overwrite,
	}
}
