package devenv

import (
	"fmt"
	"strings"

	"github.com/Quantum-Serendipity/qsdev/internal/ecosystem"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// GenerateSecretSpecToml produces a secretspec.toml file describing the secrets
// required by the project's services and ecosystem modules. It returns nil, nil
// when no secrets are declared.
func GenerateSecretSpecToml(answers types.WizardAnswers, registry *ecosystem.Registry) (*types.GeneratedFile, error) {
	var decls []ecosystem.SecretDecl

	// Collect from services.
	for _, svc := range answers.Services {
		decls = append(decls, ServiceSecretDeclarations(svc.Name)...)
	}

	// Collect from ecosystem modules implementing SecretDeclarer.
	if registry != nil {
		for _, lang := range answers.Languages {
			mod, ok := registry.ByName(lang.Name)
			if !ok {
				continue
			}
			declarer, ok := mod.(ecosystem.SecretDeclarer)
			if !ok {
				continue
			}
			cfg := toModuleConfig(lang)
			decls = append(decls, declarer.SecretDeclarations(cfg)...)
		}
	}

	if len(decls) == 0 {
		return nil, nil
	}

	// Deduplicate by Name (first occurrence wins).
	seen := make(map[string]bool)
	var unique []ecosystem.SecretDecl
	for _, d := range decls {
		if seen[d.Name] {
			continue
		}
		seen[d.Name] = true
		unique = append(unique, d)
	}

	var b strings.Builder
	b.WriteString("# Secret specification — generated by qsdev.\n")
	b.WriteString("# This file declares the secrets required by the project.\n")
	b.WriteString("# Do NOT store actual secret values in this file.\n\n")

	// Providers section.
	sources := collectSources(unique)
	b.WriteString("[providers]\n")
	for _, src := range sources {
		fmt.Fprintf(&b, "%s = \"env\"\n", src)
	}
	b.WriteString("\n")

	// Per-secret blocks.
	for _, d := range unique {
		fmt.Fprintf(&b, "[secrets.%s]\n", d.Name)
		fmt.Fprintf(&b, "description = %q\n", d.Description)
		fmt.Fprintf(&b, "required = %t\n", d.Required)
		fmt.Fprintf(&b, "source = %q\n", d.Source)
		if d.AutoGenerate {
			b.WriteString("auto_generate = true\n")
			if d.GenerateSpec != nil {
				fmt.Fprintf(&b, "generate_length = %d\n", d.GenerateSpec.Length)
				fmt.Fprintf(&b, "generate_charset = %q\n", d.GenerateSpec.Charset)
			}
		}
		b.WriteString("\n")
	}

	return &types.GeneratedFile{
		Path:     "secretspec.toml",
		Content:  []byte(b.String()),
		Mode:     0o644,
		Strategy: types.Overwrite,
		Owner:    "secretspec",
	}, nil
}

// collectSources returns the unique source identifiers from declarations,
// preserving order of first appearance.
func collectSources(decls []ecosystem.SecretDecl) []string {
	seen := make(map[string]bool)
	var sources []string
	for _, d := range decls {
		if d.Source != "" && !seen[d.Source] {
			seen[d.Source] = true
			sources = append(sources, d.Source)
		}
	}
	return sources
}
