package devenv

import (
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// GenerateCommitlintConfig produces a .commitlintrc.yml configuration file
// enforcing conventional commit message standards.
func GenerateCommitlintConfig() (*types.GeneratedFile, error) {
	var b strings.Builder

	b.WriteString("# Commitlint configuration\n")
	b.WriteString("# Generated by qsdev — do not edit manually.\n")
	b.WriteString("extends:\n")
	b.WriteString("  - '@commitlint/config-conventional'\n")
	b.WriteString("rules:\n")
	b.WriteString("  type-enum:\n")
	b.WriteString("    - 2\n")
	b.WriteString("    - always\n")
	b.WriteString("    - - build\n")
	b.WriteString("      - chore\n")
	b.WriteString("      - ci\n")
	b.WriteString("      - docs\n")
	b.WriteString("      - feat\n")
	b.WriteString("      - fix\n")
	b.WriteString("      - perf\n")
	b.WriteString("      - refactor\n")
	b.WriteString("      - revert\n")
	b.WriteString("      - style\n")
	b.WriteString("      - test\n")
	b.WriteString("  subject-case:\n")
	b.WriteString("    - 2\n")
	b.WriteString("    - never\n")
	b.WriteString("    - - sentence-case\n")
	b.WriteString("      - start-case\n")
	b.WriteString("      - pascal-case\n")
	b.WriteString("      - upper-case\n")
	b.WriteString("  header-max-length:\n")
	b.WriteString("    - 2\n")
	b.WriteString("    - always\n")
	b.WriteString("    - 100\n")

	return &types.GeneratedFile{
		Path:     ".commitlintrc.yml",
		Content:  []byte(b.String()),
		Mode:     0o644,
		Strategy: types.Overwrite,
		Owner:    "commitlint",
	}, nil
}
