package devenv_test

import (
	"strings"
	"testing"

	"github.com/Quantum-Serendipity/qsdev/addons/devenv"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

func TestGenerateCliffToml_Content(t *testing.T) {
	answers := types.WizardAnswers{}

	gf, err := devenv.GenerateCliffToml(answers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if gf == nil {
		t.Fatal("expected non-nil GeneratedFile")
	}

	content := string(gf.Content)

	// Check [changelog] section.
	if !strings.Contains(content, "[changelog]") {
		t.Error("expected [changelog] section")
	}
	if !strings.Contains(content, "header = \"\"\"") {
		t.Error("expected header in changelog section")
	}
	if !strings.Contains(content, "body = \"\"\"") {
		t.Error("expected body template in changelog section")
	}

	// Check Tera-style template markers.
	if !strings.Contains(content, "{% if version %}") {
		t.Error("expected version conditional in body template")
	}
	if !strings.Contains(content, "{% for group, commits in commits") {
		t.Error("expected group iteration in body template")
	}

	// Check [git] section.
	if !strings.Contains(content, "[git]") {
		t.Error("expected [git] section")
	}
	if !strings.Contains(content, "conventional_commits = true") {
		t.Error("expected conventional_commits = true")
	}
	if !strings.Contains(content, "protect_breaking_commits = true") {
		t.Error("expected protect_breaking_commits = true")
	}

	// Check commit parsers.
	if !strings.Contains(content, "commit_parsers = [") {
		t.Error("expected commit_parsers array")
	}
	expectedGroups := []string{
		`"Features"`, `"Bug Fixes"`, `"Performance"`, `"Refactor"`,
		`"Documentation"`, `"Testing"`, `"Miscellaneous"`,
	}
	for _, group := range expectedGroups {
		if !strings.Contains(content, group) {
			t.Errorf("expected commit parser group %s", group)
		}
	}

	// Check conventional commit prefixes.
	expectedPrefixes := []string{
		`"^feat"`, `"^fix"`, `"^perf"`, `"^refactor"`,
		`"^docs"`, `"^test"`, `"^chore"`,
	}
	for _, prefix := range expectedPrefixes {
		if !strings.Contains(content, prefix) {
			t.Errorf("expected commit parser prefix %s", prefix)
		}
	}
}

func TestGenerateCliffToml_Metadata(t *testing.T) {
	answers := types.WizardAnswers{}

	gf, err := devenv.GenerateCliffToml(answers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if gf == nil {
		t.Fatal("expected non-nil GeneratedFile")
	}

	if gf.Path != "cliff.toml" {
		t.Errorf("expected path cliff.toml, got %q", gf.Path)
	}
	if gf.Mode != 0o644 {
		t.Errorf("expected mode 0644, got %04o", gf.Mode)
	}
	if gf.Strategy != types.Overwrite {
		t.Errorf("expected strategy Overwrite, got %v", gf.Strategy)
	}
	if gf.Owner != "changelog" {
		t.Errorf("expected owner changelog, got %q", gf.Owner)
	}
}

func TestGenerateCliffToml_HasHeader(t *testing.T) {
	answers := types.WizardAnswers{}

	gf, err := devenv.GenerateCliffToml(answers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(gf.Content)

	// Should have generated-by comment.
	if !strings.Contains(content, "generated by qsdev") {
		t.Error("expected generated-by comment")
	}

	// Should have git-cliff docs reference.
	if !strings.Contains(content, "git-cliff.org") {
		t.Error("expected git-cliff.org reference")
	}
}

func TestGenerateCliffToml_TagPattern(t *testing.T) {
	answers := types.WizardAnswers{}

	gf, err := devenv.GenerateCliffToml(answers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(gf.Content)

	if !strings.Contains(content, `tag_pattern = "v[0-9]*"`) {
		t.Error("expected tag_pattern for semver tags")
	}
}
