package devenv_test

import (
	"strings"
	"testing"

	"github.com/Quantum-Serendipity/qsdev/addons/devenv"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

func TestGenerateCommitlintConfig_Content(t *testing.T) {
	file, err := devenv.GenerateCommitlintConfig()
	if err != nil {
		t.Fatalf("GenerateCommitlintConfig returned error: %v", err)
	}

	content := string(file.Content)

	// Must extend conventional config.
	if !strings.Contains(content, "@commitlint/config-conventional") {
		t.Error("missing @commitlint/config-conventional extends")
	}

	// Must have type-enum rule.
	if !strings.Contains(content, "type-enum:") {
		t.Error("missing type-enum rule")
	}

	// Must include standard commit types.
	expectedTypes := []string{"build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test"}
	for _, ct := range expectedTypes {
		if !strings.Contains(content, "- "+ct) {
			t.Errorf("missing commit type %q in type-enum", ct)
		}
	}

	// Must have subject-case rule forbidding specific cases.
	if !strings.Contains(content, "subject-case:") {
		t.Error("missing subject-case rule")
	}
	forbiddenCases := []string{"sentence-case", "start-case", "pascal-case", "upper-case"}
	for _, fc := range forbiddenCases {
		if !strings.Contains(content, fc) {
			t.Errorf("missing forbidden case %q in subject-case rule", fc)
		}
	}

	// Must have header-max-length rule.
	if !strings.Contains(content, "header-max-length:") {
		t.Error("missing header-max-length rule")
	}
	if !strings.Contains(content, "- 100") {
		t.Error("header-max-length should be 100")
	}

	// Should contain generation comment.
	if !strings.Contains(content, "Generated by qsdev") {
		t.Error("missing generation header comment")
	}
}

func TestGenerateCommitlintConfig_Metadata(t *testing.T) {
	file, err := devenv.GenerateCommitlintConfig()
	if err != nil {
		t.Fatalf("GenerateCommitlintConfig returned error: %v", err)
	}

	if file.Path != ".commitlintrc.yml" {
		t.Errorf("expected path .commitlintrc.yml, got %q", file.Path)
	}

	if file.Mode != 0o644 {
		t.Errorf("expected mode 0644, got %o", file.Mode)
	}

	if file.Strategy != types.Overwrite {
		t.Errorf("expected strategy Overwrite, got %s", file.Strategy)
	}

	if file.Owner != "commitlint" {
		t.Errorf("expected owner 'commitlint', got %q", file.Owner)
	}
}
