package devenv

import (
	"strings"

	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// GenerateCliffToml produces a cliff.toml configuration file for git-cliff,
// the changelog generator. The configuration follows the firm's standard format
// with conventional commit parsing.
func GenerateCliffToml(_ types.WizardAnswers) (*types.GeneratedFile, error) {
	var b strings.Builder

	// [changelog] section
	b.WriteString("# git-cliff configuration — generated by qsdev.\n")
	b.WriteString("# See https://git-cliff.org/docs/configuration for reference.\n\n")

	b.WriteString("[changelog]\n")
	b.WriteString("header = \"\"\"\n")
	b.WriteString("# Changelog\n\n")
	b.WriteString("All notable changes to this project will be documented in this file.\n")
	b.WriteString("\"\"\"\n\n")

	b.WriteString("body = \"\"\"\n")
	b.WriteString("{% if version %}\\\n")
	b.WriteString("    ## [{{ version | trim_start_matches(pat=\"v\") }}] - {{ timestamp | date(format=\"%Y-%m-%d\") }}\n")
	b.WriteString("{% else %}\\\n")
	b.WriteString("    ## [unreleased]\n")
	b.WriteString("{% endif %}\\\n")
	b.WriteString("{% for group, commits in commits | group_by(attribute=\"group\") %}\n")
	b.WriteString("    ### {{ group | striptags | trim | upper_first }}\n")
	b.WriteString("    {% for commit in commits %}\n")
	b.WriteString("    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\\\n")
	b.WriteString("        {% if commit.breaking %}[**breaking**] {% endif %}\\\n")
	b.WriteString("        {{ commit.message | upper_first }}\\\n")
	b.WriteString("        ({{ commit.id | truncate(length=7, end=\"\") }})\n")
	b.WriteString("    {%- endfor %}\n")
	b.WriteString("{% endfor %}\n")
	b.WriteString("\"\"\"\n\n")

	b.WriteString("trim = true\n\n")

	// [git] section
	b.WriteString("[git]\n")
	b.WriteString("conventional_commits = true\n")
	b.WriteString("filter_unconventional = true\n")
	b.WriteString("split_commits = false\n")
	b.WriteString("protect_breaking_commits = true\n")
	b.WriteString("filter_commits = false\n")
	b.WriteString("tag_pattern = \"v[0-9]*\"\n")
	b.WriteString("sort_commits = \"oldest\"\n\n")

	b.WriteString("commit_parsers = [\n")
	b.WriteString("  { message = \"^feat\", group = \"Features\" },\n")
	b.WriteString("  { message = \"^fix\", group = \"Bug Fixes\" },\n")
	b.WriteString("  { message = \"^perf\", group = \"Performance\" },\n")
	b.WriteString("  { message = \"^refactor\", group = \"Refactor\" },\n")
	b.WriteString("  { message = \"^docs\", group = \"Documentation\" },\n")
	b.WriteString("  { message = \"^test\", group = \"Testing\" },\n")
	b.WriteString("  { message = \"^chore\", group = \"Miscellaneous\" },\n")
	b.WriteString("  { message = \"^style\", group = \"Styling\" },\n")
	b.WriteString("  { message = \"^ci\", group = \"CI\" },\n")
	b.WriteString("  { message = \"^build\", group = \"Build\" },\n")
	b.WriteString("]\n")

	return &types.GeneratedFile{
		Path:     "cliff.toml",
		Content:  []byte(b.String()),
		Mode:     0o644,
		Strategy: types.Overwrite,
		Owner:    "changelog",
	}, nil
}
