package config

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"

	"gopkg.in/yaml.v3"

	"github.com/Quantum-Serendipity/qsdev/pkg/branding"
	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// projectConfigHeader is written at the top of every generated .qsdev.yaml.
const projectConfigHeader = "# qsdev project configuration — generated by qsdev init.\n# See: qsdev config --help\n"

// AnswersToConfig converts wizard answers into the committed .qsdev.yaml.
// Join mode rebuilds a teammate's answers from this file through
// ConfigToAnswers, so every choice that shapes generation and has a config
// key is persisted here. binaryVersion is the running qsdev version; it is
// recorded as a minimum version constraint (never an exact pin, which would
// fail every teammate or CI runner on a newer release).
func AnswersToConfig(answers types.WizardAnswers, binaryVersion string) types.QsdevConfig {
	cfg := types.QsdevConfig{
		Version:      types.ConfigVersionCurrent,
		QsdevVersion: MinimumVersionConstraint(binaryVersion),
		Tier:         answers.Tier,
		Profile:      answers.ProjectTypeProfile,
		InfraProfile: answers.ProfileName,
		Packages:     slices.Clone(answers.ExtraPackages),
		Overlays:     slices.Clone(answers.Overlays),
	}

	for _, lang := range answers.Languages {
		cfg.Languages = append(cfg.Languages, types.LanguageConfig{
			Name:           lang.Name,
			Version:        lang.Version,
			PackageManager: lang.PackageManager,
		})
	}

	for _, svc := range answers.Services {
		cfg.Services = append(cfg.Services, types.ServiceConfig{
			Name:    svc.Name,
			Version: svc.Version,
			Options: maps.Clone(svc.Settings),
		})
	}

	cfg.Security = types.SecurityConfig{
		Level: answers.ComplianceLevel,
	}

	// Always record claude_code.enabled, including false: an absent key is
	// read back as enabled (the legacy default), so omitting it would turn a
	// deliberate --claude-code=false / --devenv-only project back on for
	// every teammate who joins.
	enabled := answers.ClaudeCode
	cfg.ClaudeCode = types.ClaudeCodeConfig{Enabled: &enabled}
	if answers.ClaudeCode {
		cfg.ClaudeCode.PermissionLevel = answers.PermissionLevel
		cfg.ClaudeCode.Skills = answers.Skills
		cfg.ClaudeCode.MCPServers = answers.MCPServers
	}

	// Tool decisions carry the toggles (safety-block, agent tools) and the
	// tier-derived tool set that have no dedicated config key.
	for _, name := range slices.Sorted(maps.Keys(answers.EnabledTools)) {
		if answers.EnabledTools[name] {
			cfg.Tools.Enabled = append(cfg.Tools.Enabled, name)
		} else {
			cfg.Tools.Disabled = append(cfg.Tools.Disabled, name)
		}
	}

	cfg.Infrastructure = types.InfraConfig{
		RegistryProxy:          answers.Infrastructure.RegistryProxy,
		RegistryProxyOverrides: maps.Clone(answers.Infrastructure.RegistryProxyOverrides),
		RegistryProxyPaths:     maps.Clone(answers.Infrastructure.RegistryProxyPaths),
		NixCache:               answers.Infrastructure.NixCache,
		BuildCache:             answers.Infrastructure.BuildCache,
	}

	return cfg
}

// olderSchema reports whether the .qsdev.yaml content data declares a schema
// version older than the current one. data has already parsed, so its
// version is present and valid.
func olderSchema(data []byte) bool {
	var head struct {
		Version any `yaml:"version"`
	}
	if err := yaml.Unmarshal(data, &head); err != nil {
		return false
	}
	v, ok := toInt(head.Version)
	return ok && v < types.ConfigVersionCurrent
}

// MarshalProjectConfig renders cfg as .qsdev.yaml content, header included,
// in the layout init and SyncProjectConfig write.
func MarshalProjectConfig(cfg types.QsdevConfig) ([]byte, error) {
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return nil, fmt.Errorf("marshaling config: %w", err)
	}
	return append([]byte(projectConfigHeader), data...), nil
}

// WriteProjectConfig atomically writes cfg to path as .qsdev.yaml content.
func WriteProjectConfig(path string, cfg types.QsdevConfig) error {
	content, err := MarshalProjectConfig(cfg)
	if err != nil {
		return err
	}
	if err := fileutil.WriteFileAtomic(path, content, fileutil.ModeReadWrite); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// SyncProjectConfig records the choices that day-2 commands change (devenv
// add/remove-*, enable/disable, update, claude subcommands) in the committed
// .qsdev.yaml, the only team-shared configuration. Those commands update the
// gitignored answers file; without this a teammate's `qsdev init --mode join`
// would rebuild the environment from a stale config and drop them.
//
// Only answer-derived keys are replaced (tier, languages, services, packages,
// overlays, claude_code and tool decisions); keys the answers do not carry
// (qsdev_version, security, profile, infra_profile, infrastructure, client,
// git, tools.config) are kept as committed. A project without .qsdev.yaml
// (e.g. a standalone `devenv init`) is left alone, and the file is rewritten
// only when a synced key actually changed or it is at an older schema
// version, which is thereby migrated to the current one.
func SyncProjectConfig(projectRoot string, answers types.WizardAnswers) error {
	cfgFile := branding.Get().ConfigFile
	path := filepath.Join(projectRoot, cfgFile)
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("updating %s: reading config file %s: %w", cfgFile, path, err)
	}
	current, err := ParseQsdevConfigBytes(data)
	if err != nil {
		return fmt.Errorf("updating %s: %w", cfgFile, err)
	}

	fresh := AnswersToConfig(answers, "")
	synced := *current
	if fresh.Tier != "" {
		synced.Tier = fresh.Tier
	}
	synced.Languages = fresh.Languages
	synced.Services = fresh.Services
	synced.Packages = fresh.Packages
	synced.Overlays = fresh.Overlays
	synced.ClaudeCode = fresh.ClaudeCode
	synced.Tools.Enabled = fresh.Tools.Enabled
	synced.Tools.Disabled = fresh.Tools.Disabled

	before, err := MarshalProjectConfig(*current)
	if err != nil {
		return err
	}
	after, err := MarshalProjectConfig(synced)
	if err != nil {
		return err
	}
	if bytes.Equal(before, after) && !olderSchema(data) {
		return nil
	}
	if err := WriteProjectConfig(path, synced); err != nil {
		return fmt.Errorf("updating %s: %w", cfgFile, err)
	}
	return nil
}
