package mcpregistry

// knownServers defines the built-in MCP server definitions that ship with qsdev.
// These mirror the knownMCPServers map in addons/claudecode/generate_mcp.go but
// carry enriched metadata for the registry.
var knownServers = []McpServerDefinition{
	// --- Integration servers ---
	{
		Name:        "github",
		DisplayName: "GitHub MCP",
		Category:    CategoryIntegration,
		Description: "GitHub repository and issue management",
		Command:     "npx",
		Args:        []string{"@anthropic-ai/mcp-github"},
		Env:         map[string]string{"GITHUB_TOKEN": "${GITHUB_TOKEN}"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},
	{
		Name:        "filesystem",
		DisplayName: "Filesystem MCP",
		Category:    CategoryIntegration,
		Description: "Local filesystem access",
		Command:     "npx",
		Args:        []string{"@anthropic-ai/mcp-filesystem"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},
	{
		Name:        "postgres",
		DisplayName: "PostgreSQL MCP",
		Category:    CategoryIntegration,
		Description: "PostgreSQL database access",
		Command:     "npx",
		Args:        []string{"@anthropic-ai/mcp-postgres"},
		Env:         map[string]string{"DATABASE_URL": "${DATABASE_URL}"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},
	{
		Name:        "fetch",
		DisplayName: "Fetch MCP",
		Category:    CategoryIntegration,
		Description: "HTTP fetch for web content retrieval",
		Command:     "npx",
		Args:        []string{"@anthropic-ai/mcp-fetch"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},

	// --- Security servers ---
	{
		Name:        "socket",
		DisplayName: "Socket.dev Security",
		Category:    CategorySecurity,
		Description: "Supply chain security analysis of dependencies",
		Command:     "npx",
		Args:        []string{"@anthropic-ai/mcp-socket"},
		Env:         map[string]string{"SOCKET_SECURITY_API_KEY": "${SOCKET_SECURITY_API_KEY}"},
		RequiredEnv: []string{"SOCKET_SECURITY_API_KEY"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},

	// --- Agent servers ---
	{
		Name:        "semble",
		DisplayName: "Semble Semantic Search",
		Category:    CategoryAgent,
		Description: "Semantic code search across repositories",
		Command:     "uvx",
		Args:        []string{"--from", "semble[mcp]", "semble"},
		RequiredEnv: []string{"SEMBLE_API_KEY"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},
	{
		Name:        "context7",
		DisplayName: "Context7",
		Category:    CategoryAgent,
		Description: "Library documentation lookups via web",
		Command:     "npx",
		Args:        []string{"-y", "@upstash/context7-mcp"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},
	{
		Name:        "agent-postmortem",
		DisplayName: "Agent Postmortem",
		Category:    CategoryAgent,
		Description: "Session analysis and failure pattern detection",
		Command:     "qsdev",
		Args:        []string{"mcp", "agent-postmortem"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},
	{
		Name:        "version-sentinel",
		DisplayName: "Version Sentinel",
		Category:    CategoryAgent,
		Description: "Dependency version monitoring and drift detection",
		Command:     "qsdev",
		Args:        []string{"mcp", "version-sentinel"},
		Transport:   TransportStdio,
		Source:      SourceBuiltin,
	},

	// --- Documentation servers ---
	{
		Name:          "local-docs-devdocs",
		DisplayName:   "DevDocs Local Documentation",
		Category:      CategoryDocumentation,
		Description:   "Local DevDocs documentation server for offline API reference",
		Command:       "npx",
		Args:          []string{"devdocs-mcp-server"},
		Env:           map[string]string{"DEVDOCS_DATA_DIR": "${HOME}/.local/share/qsdev/docs/devdocs"},
		Transport:     TransportStdio,
		Source:        SourceBuiltin,
		InstallMethod: InstallNpmGlobal,
		PackageName:   "devdocs-mcp-server",
	},
	{
		Name:        "local-docs-zim",
		DisplayName: "Stack Exchange ZIM Documentation",
		Category:    CategoryDocumentation,
		Description: "openzim-mcp server for offline Stack Exchange via ZIM files",
		Command:     "openzim-mcp",
		Env: map[string]string{
			"OPENZIM_MCP_ZIM_DIR":   "${HOME}/.local/share/qsdev/docs/zim",
			"OPENZIM_MCP_TOOL_MODE": "simple",
			"OPENZIM_MCP_CACHE_TTL": "3600",
			"OPENZIM_MCP_LOG_LEVEL": "WARNING",
		},
		Transport:     TransportStdio,
		Source:        SourceBuiltin,
		InstallMethod: InstallUvTool,
		PackageName:   "openzim-mcp",
	},
	{
		Name:          "man-pages",
		DisplayName:   "Man Pages MCP",
		Category:      CategoryDocumentation,
		Description:   "Local man page documentation for system commands",
		Command:       "uvx",
		Args:          []string{"man-mcp-server"},
		Transport:     TransportStdio,
		Source:        SourceBuiltin,
		InstallMethod: InstallUvTool,
		PackageName:   "man-mcp-server",
	},
	{
		Name:          "mcp-nixos",
		DisplayName:   "MCP-NixOS Documentation",
		Category:      CategoryDocumentation,
		Description:   "NixOS packages, options, and Home Manager documentation",
		Command:       "uvx",
		Args:          []string{"mcp-nixos"},
		Transport:     TransportStdio,
		Source:        SourceBuiltin,
		InstallMethod: InstallUvTool,
		PackageName:   "mcp-nixos",
	},
}
