package lsp

// defaultServers returns the canonical list of all 26 LSP server configurations
// qsdev knows how to provision: 22 default-on plus 4 opt-in (default-off). The
// data is validated against current nixpkgs and upstream server docs; do not
// "correct" it without re-validating. Order here is irrelevant — the registry
// sorts by EcosystemName for deterministic output.
//
// A fresh slice with fresh configs is returned on every call so callers (the
// registry) own their copies.
func defaultServers() []*LSPServerConfig {
	return []*LSPServerConfig{
		// --- Default-on (22) ---
		{
			EcosystemName: "go",
			DisplayName:   "Go (gopls)",
			Command:       "gopls",
			Args:          []string{"serve"},
			LanguageID:    "go",
			Extensions:    []string{".go"},
			RulePatterns:  []string{"**/go.mod", "**/go.sum"},
			Settings: map[string]any{
				"analyses": map[string]any{
					"nilness":     true,
					"shadow":      true,
					"unusedwrite": true,
				},
				// Key is "vulncheck" (not "ui.vulncheck"); value "Imports".
				"vulncheck": "Imports",
			},
			NixPackage:      "gopls",
			DevenvLSPAttr:   "languages.go",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName: "javascript",
			DisplayName:   "JavaScript/TypeScript (typescript-language-server)",
			Command:       "typescript-language-server",
			Args:          []string{"--stdio"},
			LanguageID:    "typescript",
			Extensions:    []string{".ts", ".tsx", ".js", ".jsx", ".mts", ".cts"},
			InitOptions: map[string]any{
				"maxTsServerMemory": 2048,
			},
			NixPackage:      "typescript-language-server",
			DevenvLSPAttr:   "languages.javascript",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			MemoryLimitMB:   2048,
			SandboxCategory: "B",
		},
		{
			EcosystemName: "python",
			DisplayName:   "Python (pyright)",
			Command:       "pyright-langserver",
			Args:          []string{"--stdio"},
			LanguageID:    "python",
			Extensions:    []string{".py"},
			RulePatterns:  []string{"**/pyproject.toml"},
			Settings: map[string]any{
				"python.analysis.typeCheckingMode": "basic",
			},
			NixPackage:      "pyright",
			DevenvLSPAttr:   "languages.python",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName: "rust",
			DisplayName:   "Rust (rust-analyzer)",
			Command:       "rust-analyzer",
			LanguageID:    "rust",
			Extensions:    []string{".rs"},
			RulePatterns:  []string{"**/Cargo.toml", "**/Cargo.lock"},
			Settings: map[string]any{
				"check": map[string]any{
					"command": "clippy",
				},
			},
			NixPackage:      "rust-analyzer",
			DevenvLSPAttr:   "languages.rust",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "C",
		},
		{
			EcosystemName: "cpp",
			DisplayName:   "C/C++ (clangd)",
			Command:       "clangd",
			Args:          []string{"--background-index", "--clang-tidy"},
			LanguageID:    "cpp",
			Extensions:    []string{".c", ".h", ".cc", ".cpp", ".hpp", ".cxx"},
			NixPackage:    "clang-tools", // clangd ships in clang-tools.
			// TODO: confirm devenv attr is "languages.cplusplus" vs "languages.c"
			// against the pinned devenv at build time; "cplusplus" chosen per plan.
			DevenvLSPAttr:   "languages.cplusplus",
			Devenv:          DevenvEnableOverridePackage, // devenv default is ccls.
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName: "java",
			DisplayName:   "Java (jdtls)",
			Command:       "jdtls",
			LanguageID:    "java",
			Extensions:    []string{".java"},
			RulePatterns:  []string{"**/pom.xml", "**/build.gradle", "**/build.gradle.kts"},
			Settings: map[string]any{
				"java.compile.nullAnalysis.mode": "automatic",
			},
			NixPackage:      "jdt-language-server",
			DevenvLSPAttr:   "languages.java",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "C",
		},
		{
			EcosystemName:   "dotnet",
			DisplayName:     ".NET/C# (csharp-ls)",
			Command:         "csharp-ls",
			LanguageID:      "csharp",
			Extensions:      []string{".cs"},
			NixPackage:      "csharp-ls",
			DevenvLSPAttr:   "languages.dotnet",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName:   "scala",
			DisplayName:     "Scala (metals)",
			Command:         "metals",
			LanguageID:      "scala",
			Extensions:      []string{".scala", ".sbt", ".sc"},
			NixPackage:      "metals",
			DevenvLSPAttr:   "languages.scala",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName:   "elixir",
			DisplayName:     "Elixir (elixir-ls)",
			Command:         "elixir-ls",
			LanguageID:      "elixir",
			Extensions:      []string{".ex", ".exs"},
			NixPackage:      "elixir-ls", // hyphen, not elixir_ls.
			DevenvLSPAttr:   "languages.elixir",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName:   "clojure",
			DisplayName:     "Clojure (clojure-lsp)",
			Command:         "clojure-lsp",
			LanguageID:      "clojure",
			Extensions:      []string{".clj", ".cljs", ".cljc", ".edn"},
			NixPackage:      "clojure-lsp",
			DevenvLSPAttr:   "languages.clojure",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName:   "container",
			DisplayName:     "Docker (docker-language-server)",
			Command:         "docker-language-server",
			LanguageID:      "dockerfile",
			Extensions:      []string{".dockerfile"},
			RulePatterns:    []string{"**/Dockerfile", "**/Dockerfile.*"},
			NixPackage:      "docker-language-server",
			DevenvLSPAttr:   "", // no devenv lsp option; add to packages list.
			Devenv:          DevenvPackageList,
			DefaultOn:       true,
			SandboxCategory: "A",
		},
		{
			EcosystemName:   "terraform",
			DisplayName:     "Terraform (terraform-ls)",
			Command:         "terraform-ls",
			Args:            []string{"serve"},
			LanguageID:      "terraform",
			Extensions:      []string{".tf", ".tfvars"},
			NixPackage:      "terraform-ls",
			DevenvLSPAttr:   "languages.terraform",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "A",
		},
		{
			EcosystemName:   "php",
			DisplayName:     "PHP (phpactor)",
			Command:         "phpactor",
			Args:            []string{"language-server"},
			LanguageID:      "php",
			Extensions:      []string{".php"},
			NixPackage:      "phpactor",
			DevenvLSPAttr:   "languages.php",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName:   "ruby",
			DisplayName:     "Ruby (ruby-lsp)",
			Command:         "ruby-lsp",
			LanguageID:      "ruby",
			Extensions:      []string{".rb"},
			NixPackage:      "ruby-lsp",
			DevenvLSPAttr:   "languages.ruby",
			Devenv:          DevenvEnableOverridePackage, // devenv default is solargraph.
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName:   "shell",
			DisplayName:     "Shell (bash-language-server)",
			Command:         "bash-language-server",
			Args:            []string{"start"},
			LanguageID:      "shellscript",
			Extensions:      []string{".sh", ".bash"},
			NixPackage:      "bash-language-server",
			DevenvLSPAttr:   "languages.shell",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "A",
		},
		{
			EcosystemName:   "helm",
			DisplayName:     "Helm (helm-ls)",
			Command:         "helm_ls",
			Args:            []string{"serve"},
			LanguageID:      "helm",
			Extensions:      []string{".yaml", ".tpl"},
			RulePatterns:    []string{"**/Chart.yaml", "**/templates/**"},
			NixPackage:      "helm-ls",
			DevenvLSPAttr:   "", // no devenv lsp option; add to packages list.
			Devenv:          DevenvPackageList,
			DefaultOn:       true,
			SandboxCategory: "A",
		},
		{
			EcosystemName:   "nix",
			DisplayName:     "Nix (nixd)",
			Command:         "nixd",
			LanguageID:      "nix",
			Extensions:      []string{".nix"},
			RulePatterns:    []string{"**/flake.nix", "**/flake.lock"},
			NixPackage:      "nixd",
			DevenvLSPAttr:   "languages.nix",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "A",
		},
		{
			EcosystemName:   "perl",
			DisplayName:     "Perl (perlnavigator)",
			Command:         "perlnavigator",
			Args:            []string{"--stdio"},
			LanguageID:      "perl",
			Extensions:      []string{".pl", ".pm"},
			NixPackage:      "perlnavigator",
			DevenvLSPAttr:   "languages.perl",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "A",
		},
		{
			EcosystemName:   "lua",
			DisplayName:     "Lua (lua-language-server)",
			Command:         "lua-language-server",
			LanguageID:      "lua",
			Extensions:      []string{".lua"},
			NixPackage:      "lua-language-server",
			DevenvLSPAttr:   "languages.lua",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "A",
		},
		{
			EcosystemName:   "zig",
			DisplayName:     "Zig (zls)",
			Command:         "zls",
			LanguageID:      "zig",
			Extensions:      []string{".zig"},
			NixPackage:      "zls",
			DevenvLSPAttr:   "languages.zig",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "A",
		},
		{
			EcosystemName:   "dart",
			DisplayName:     "Dart (dart language-server)",
			Command:         "dart",
			Args:            []string{"language-server"},
			LanguageID:      "dart",
			Extensions:      []string{".dart"},
			NixPackage:      "", // server ships in pkgs.dart (SDK-bundled).
			DevenvLSPAttr:   "",
			Devenv:          DevenvSDKBundled,
			DefaultOn:       true,
			SandboxCategory: "B",
		},
		{
			EcosystemName:   "r",
			DisplayName:     "R (languageserver)",
			Command:         "R",
			Args:            []string{"--slave", "-e", "languageserver::run()"},
			LanguageID:      "r",
			Extensions:      []string{".R", ".r"},
			NixPackage:      "rPackages.languageserver",
			DevenvLSPAttr:   "languages.r",
			Devenv:          DevenvEnable,
			DefaultOn:       true,
			SandboxCategory: "B",
		},

		// --- Default-off / opt-in (4) ---
		{
			EcosystemName:   "kotlin",
			DisplayName:     "Kotlin (kotlin-language-server)",
			Command:         "kotlin-language-server",
			LanguageID:      "kotlin",
			Extensions:      []string{".kt", ".kts"},
			NixPackage:      "kotlin-language-server",
			DevenvLSPAttr:   "languages.kotlin",
			Devenv:          DevenvDisable,
			DefaultOn:       false,
			Caveats:         "fwcd server in maintenance limbo; JetBrains kotlin-lsp pre-1.0, not yet in nixpkgs",
			SandboxCategory: "C",
		},
		{
			EcosystemName:   "haskell",
			DisplayName:     "Haskell (haskell-language-server)",
			Command:         "haskell-language-server-wrapper",
			Args:            []string{"--lsp"},
			LanguageID:      "haskell",
			Extensions:      []string{".hs", ".lhs"},
			NixPackage:      "haskell-language-server",
			DevenvLSPAttr:   "languages.haskell",
			Devenv:          DevenvDisable,
			DefaultOn:       false,
			Caveats:         "2-3 GB RAM typical; GHC version coupling",
			SandboxCategory: "C",
		},
		{
			EcosystemName:   "swift",
			DisplayName:     "Swift (sourcekit-lsp)",
			Command:         "sourcekit-lsp",
			LanguageID:      "swift",
			Extensions:      []string{".swift"},
			NixPackage:      "sourcekit-lsp",
			DevenvLSPAttr:   "languages.swift",
			Devenv:          DevenvDisable,
			DefaultOn:       false,
			Caveats:         "heavy toolchain build; opt-in",
			SandboxCategory: "C",
		},
		{
			EcosystemName:   "ansible",
			DisplayName:     "Ansible (ansible-language-server)",
			Command:         "ansible-language-server",
			Args:            []string{"--stdio"},
			LanguageID:      "ansible",
			Extensions:      []string{".yml", ".yaml"},
			NixPackage:      "ansible-language-server",
			DevenvLSPAttr:   "", // no devenv lsp option; add to packages list when opted in.
			Devenv:          DevenvPackageList,
			DefaultOn:       false,
			Caveats:         "opt-in",
			SandboxCategory: "B",
		},
	}
}
