package devinit

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/Quantum-Serendipity/qsdev/pkg/branding"
)

// enableCmd creates the `qsdev enable <tool>` command.
func enableCmd() *cobra.Command {
	var opts enableOptions

	cmd := &cobra.Command{
		Use:   "enable <tool>",
		Short: "Enable a tool in the current project",
		Long: fmt.Sprintf(`Enable a tool and generate its configuration files.

The tool's prerequisites are validated before enabling. Shared files (like
CLAUDE.md, devenv.nix or settings.json) are regenerated and merged exactly as
'%[1]s update' would, preserving your edits; the tool's own files are written
fresh. Existing files %[1]s did not generate are never overwritten unless
--force is given. Use '%[1]s list' to see available tools.`, branding.Get().AppName),
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runEnable(cmd, args[0], opts)
		},
	}

	cmd.Flags().BoolVar(&opts.DryRun, "dry-run", false, "Preview changes without writing files")
	cmd.Flags().BoolVar(&opts.Force, "force", false, "Overwrite existing tool files that were not generated by "+branding.Get().AppName)

	return cmd
}

// disableCmd creates the `qsdev disable <tool>` command.
func disableCmd() *cobra.Command {
	var opts disableOptions

	cmd := &cobra.Command{
		Use:   "disable <tool>",
		Short: "Disable a tool in the current project",
		Long: `Disable a tool and remove its configuration files.

Files exclusively owned by the tool are deleted. Shared files are
regenerated without the tool's contribution, preserving your edits. If any
owned file has been modified by the user, the command warns and exits unless
--force is specified.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDisable(cmd, args[0], opts)
		},
	}

	cmd.Flags().BoolVar(&opts.Force, "force", false, "Remove files even if they have been modified by the user")

	return cmd
}

// listCmd creates the `qsdev list` command.
func listCmd() *cobra.Command {
	var opts listOptions

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List all available tools",
		Long: `List all registered tools grouped by category.

Use --category to filter by a specific category (security, ai-agent,
devex, infrastructure).`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runList(cmd, opts)
		},
	}

	cmd.Flags().StringVar(&opts.Category, "category", "", "Filter by category (security, ai-agent, devex, infrastructure)")

	return cmd
}

type enableOptions struct {
	DryRun bool
	Force  bool
}

type disableOptions struct {
	Force bool
}

type listOptions struct {
	Category string
}
