package devinit

import (
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

func buildQsdevConfig(answers types.WizardAnswers, qsdevVersion string) types.QsdevConfig {
	cfg := types.QsdevConfig{
		Version:      types.ConfigVersionCurrent,
		QsdevVersion: qsdevVersion,
		Profile:      answers.ProfileName,
	}

	for _, lang := range answers.Languages {
		cfg.Languages = append(cfg.Languages, types.LanguageConfig{
			Name:           lang.Name,
			Version:        lang.Version,
			PackageManager: lang.PackageManager,
		})
	}

	for _, svc := range answers.Services {
		cfg.Services = append(cfg.Services, types.ServiceConfig{
			Name:    svc.Name,
			Version: svc.Version,
		})
	}

	cfg.Security = types.SecurityConfig{
		Level: answers.ComplianceLevel,
	}

	if answers.ClaudeCode {
		enabled := true
		cfg.ClaudeCode = types.ClaudeCodeConfig{
			Enabled:         &enabled,
			PermissionLevel: answers.PermissionLevel,
			Skills:          answers.Skills,
			MCPServers:      answers.MCPServers,
		}
	}

	cfg.Infrastructure = types.InfraConfig{
		RegistryProxy:          answers.Infrastructure.RegistryProxy,
		RegistryProxyOverrides: answers.Infrastructure.RegistryProxyOverrides,
		NixCache:               answers.Infrastructure.NixCache,
		BuildCache:             answers.Infrastructure.BuildCache,
	}

	return cfg
}

func writeQsdevConfig(path string, cfg types.QsdevConfig) error {
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	header := []byte("# qsdev project configuration — generated by qsdev init.\n# See: qsdev config --help\n")
	content := append(header, data...)

	return fileutil.WriteFileAtomic(path, content, 0o644)
}
