package devinit

import (
	"fmt"
	"maps"
	"slices"

	"gopkg.in/yaml.v3"

	"github.com/Quantum-Serendipity/qsdev/pkg/fileutil"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// buildQsdevConfig converts the create path's answers into the committed
// .qsdev.yaml. Join mode rebuilds a teammate's answers from this file through
// config.ConfigToAnswers, so every choice that shapes generation and has a
// config key is persisted here.
func buildQsdevConfig(answers types.WizardAnswers, qsdevVersion string) types.QsdevConfig {
	cfg := types.QsdevConfig{
		Version:      types.ConfigVersionCurrent,
		QsdevVersion: qsdevVersion,
		Tier:         answers.Tier,
		Profile:      answers.ProfileName,
	}

	for _, lang := range answers.Languages {
		cfg.Languages = append(cfg.Languages, types.LanguageConfig{
			Name:           lang.Name,
			Version:        lang.Version,
			PackageManager: lang.PackageManager,
		})
	}

	for _, svc := range answers.Services {
		cfg.Services = append(cfg.Services, types.ServiceConfig{
			Name:    svc.Name,
			Version: svc.Version,
			Options: maps.Clone(svc.Settings),
		})
	}

	cfg.Security = types.SecurityConfig{
		Level: answers.ComplianceLevel,
	}

	// Always record claude_code.enabled, including false: an absent key is
	// read back as enabled (the legacy default), so omitting it would turn a
	// deliberate --claude-code=false / --devenv-only project back on for
	// every teammate who joins.
	enabled := answers.ClaudeCode
	cfg.ClaudeCode = types.ClaudeCodeConfig{Enabled: &enabled}
	if answers.ClaudeCode {
		cfg.ClaudeCode.PermissionLevel = answers.PermissionLevel
		cfg.ClaudeCode.Skills = answers.Skills
		cfg.ClaudeCode.MCPServers = answers.MCPServers
	}

	// Tool decisions carry the toggles (safety-block, agent tools) and the
	// tier-derived tool set that have no dedicated config key.
	for _, name := range slices.Sorted(maps.Keys(answers.EnabledTools)) {
		if answers.EnabledTools[name] {
			cfg.Tools.Enabled = append(cfg.Tools.Enabled, name)
		} else {
			cfg.Tools.Disabled = append(cfg.Tools.Disabled, name)
		}
	}

	cfg.Infrastructure = types.InfraConfig{
		RegistryProxy:          answers.Infrastructure.RegistryProxy,
		RegistryProxyOverrides: maps.Clone(answers.Infrastructure.RegistryProxyOverrides),
		RegistryProxyPaths:     maps.Clone(answers.Infrastructure.RegistryProxyPaths),
		NixCache:               answers.Infrastructure.NixCache,
		BuildCache:             answers.Infrastructure.BuildCache,
	}

	return cfg
}

func writeQsdevConfig(path string, cfg types.QsdevConfig) error {
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	header := []byte("# qsdev project configuration — generated by qsdev init.\n# See: qsdev config --help\n")
	content := append(header, data...)

	return fileutil.WriteFileAtomic(path, content, fileutil.ModeReadWrite)
}
