package devinit

import (
	"testing"

	"github.com/Quantum-Serendipity/qsdev/internal/tier"
	"github.com/Quantum-Serendipity/qsdev/internal/toolreg"
	"github.com/Quantum-Serendipity/qsdev/pkg/types"
)

// generatedPaths runs the accumulator and returns the set of generated paths
// with their owners.
func generatedPaths(t *testing.T, answers types.WizardAnswers, scope generationScope) map[string]string {
	t.Helper()
	acc, err := runAccumulator(answers, scope)
	if err != nil {
		t.Fatalf("runAccumulator: %v", err)
	}
	out := make(map[string]string, len(acc.allFiles))
	for _, f := range acc.allFiles {
		out[f.Path] = f.Owner
	}
	return out
}

// TestRunAccumulator_ToolFilesIndependentOfClaudeCode verifies that the files
// of enabled non-agent tools are generated by init/update/join/repair whether
// or not Claude Code is configured, in every generation scope, and below the
// Full tier (F519).
func TestRunAccumulator_ToolFilesIndependentOfClaudeCode(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name   string
		claude bool
		tier   string
		scope  generationScope
	}{
		{"claude code off, full", false, "full", generationScope{}},
		{"claude code on, standard", true, "standard", generationScope{}},
		{"claude code off, supply-chain-only", false, "supply-chain-only", generationScope{}},
		{"devenv-only scope", true, "full", generationScope{DevenvOnly: true}},
		{"claude-only scope", true, "full", generationScope{ClaudeOnly: true}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			answers := types.WizardAnswers{
				ProjectName:  "demo",
				ProjectRoot:  t.TempDir(),
				Tier:         tc.tier,
				ClaudeCode:   tc.claude,
				Languages:    []types.LanguageChoice{{Name: "go"}},
				EnabledTools: map[string]bool{"changelog": true, "starship-integration": true},
			}
			got := generatedPaths(t, answers, tc.scope)
			for path, owner := range map[string]string{"cliff.toml": "changelog", ".starship.toml": "starship-integration"} {
				gotOwner, ok := got[path]
				if !ok {
					t.Errorf("%s not generated", path)
					continue
				}
				if gotOwner != owner {
					t.Errorf("%s owner = %q, want %q", path, gotOwner, owner)
				}
			}
		})
	}
}

// TestToolFilesGenerator_TierDefaults covers the always-on and
// on-when-detected tools the producer took over from the claudecode
// generator: present from the standard tier, absent at supply-chain-only,
// generated once, and suppressed when force-disabled.
func TestToolFilesGenerator_TierDefaults(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name    string
		tier    string
		enabled map[string]bool
		want    map[string]bool
	}{
		{
			name: "standard emits always-on tools",
			tier: "standard",
			want: map[string]bool{".gitleaks.toml": true, ".semgrepignore": true},
		},
		{
			name: "full emits always-on tools",
			tier: "full",
			want: map[string]bool{".gitleaks.toml": true, ".semgrepignore": true},
		},
		{
			name: "supply-chain-only emits no tool defaults",
			tier: "supply-chain-only",
			want: map[string]bool{".gitleaks.toml": false, ".semgrepignore": false},
		},
		{
			name:    "force-disabled always-on tool is not regenerated",
			tier:    "standard",
			enabled: map[string]bool{"gitleaks": false},
			want:    map[string]bool{".gitleaks.toml": false, ".semgrepignore": true},
		},
		{
			name:    "detected tool emits from standard",
			tier:    "standard",
			enabled: map[string]bool{"container-security": true},
			want:    map[string]bool{".grype.yaml": true},
		},
		{
			name:    "detected tool not emitted at supply-chain-only",
			tier:    "supply-chain-only",
			enabled: map[string]bool{"container-security": true},
			want:    map[string]bool{".grype.yaml": false},
		},
		{
			name:    "opt-in tool follows the explicit choice at supply-chain-only",
			tier:    "supply-chain-only",
			enabled: map[string]bool{"commitlint": true},
			want:    map[string]bool{".commitlintrc.yml": true},
		},
	}
	gen := toolFilesGenerator{registry: toolreg.DefaultRegistry()}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			files, err := gen.Generate(types.WizardAnswers{
				Tier:         tc.tier,
				Languages:    []types.LanguageChoice{{Name: "go"}},
				EnabledTools: tc.enabled,
			})
			if err != nil {
				t.Fatalf("Generate: %v", err)
			}
			counts := make(map[string]int, len(files))
			for _, f := range files {
				counts[f.Path]++
				if f.Owner == "" {
					t.Errorf("%s has no owner", f.Path)
				}
			}
			for path, want := range tc.want {
				if got := counts[path] > 0; got != want {
					t.Errorf("%s generated = %v, want %v", path, got, want)
				}
				if counts[path] > 1 {
					t.Errorf("%s generated %d times, want once", path, counts[path])
				}
			}
		})
	}
}

// TestToolFilesGenerator_SkipsAgentTools verifies the producer leaves every
// agent tool to the claudecode generator, even when enabled.
func TestToolFilesGenerator_SkipsAgentTools(t *testing.T) {
	t.Parallel()
	reg := toolreg.DefaultRegistry()
	enabled := make(map[string]bool)
	for _, tool := range reg.All() {
		enabled[tool.Name] = true
	}
	files, err := toolFilesGenerator{registry: reg}.Generate(types.WizardAnswers{
		Tier:         "full",
		Languages:    []types.LanguageChoice{{Name: "go"}},
		EnabledTools: enabled,
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if len(files) == 0 {
		t.Fatal("expected non-agent tool files")
	}
	for _, f := range files {
		tool, ok := reg.ByName(f.Owner)
		if !ok {
			t.Errorf("%s owned by unknown tool %q", f.Path, f.Owner)
			continue
		}
		if tool.IsAgentTool() {
			t.Errorf("%s generated for agent tool %q", f.Path, f.Owner)
		}
	}
}

func TestToolFilesWanted(t *testing.T) {
	t.Parallel()
	cases := []struct {
		policy toolreg.DefaultPolicy
		tier   tier.Tier
		entry  *bool
		want   bool
	}{
		{toolreg.AlwaysOn, tier.SupplyChainOnly, nil, false},
		{toolreg.AlwaysOn, tier.Standard, nil, true},
		{toolreg.AlwaysOn, tier.Standard, boolPtr(false), false},
		{toolreg.AlwaysOn, tier.Full, boolPtr(true), true},
		{toolreg.OnWhenDetected, tier.Standard, nil, false},
		{toolreg.OnWhenDetected, tier.SupplyChainOnly, boolPtr(true), false},
		{toolreg.OnWhenDetected, tier.Standard, boolPtr(true), true},
		{toolreg.OptIn, tier.Full, nil, false},
		{toolreg.OptIn, tier.SupplyChainOnly, boolPtr(true), true},
		{toolreg.OptIn, tier.Standard, boolPtr(false), false},
		{toolreg.AlwaysOff, tier.Full, nil, false},
		{toolreg.AlwaysOff, tier.Standard, boolPtr(true), true},
	}
	for _, tc := range cases {
		entry := "unset"
		if tc.entry != nil {
			entry = map[bool]string{true: "on", false: "off"}[*tc.entry]
		}
		t.Run(tc.policy.String()+"/"+tc.tier.String()+"/"+entry, func(t *testing.T) {
			t.Parallel()
			answers := types.WizardAnswers{EnabledTools: map[string]bool{}}
			if tc.entry != nil {
				answers.EnabledTools["x"] = *tc.entry
			}
			tool := &toolreg.Tool{Name: "x", Default: tc.policy}
			if got := toolFilesWanted(tool, answers, tc.tier); got != tc.want {
				t.Errorf("toolFilesWanted = %v, want %v", got, tc.want)
			}
		})
	}
}

func boolPtr(b bool) *bool { return &b }
